-- Minimal safe constraints for local bootstrap
-- Apply after schema_postgres.sql

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_COMMON_CODE_GROUP') THEN
    ALTER TABLE COMMON_CODE ADD CONSTRAINT FK_COMMON_CODE_GROUP FOREIGN KEY (CODE_GRP_ID) REFERENCES COMMON_CODE_GROUP(CODE_GRP_ID);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_DEPARTMENT_PARENT') THEN
    ALTER TABLE DEPARTMENT ADD CONSTRAINT FK_DEPARTMENT_PARENT FOREIGN KEY (UP_DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_USERS_DEPT') THEN
    ALTER TABLE USERS ADD CONSTRAINT FK_USERS_DEPT FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_USERS_JBGD') THEN
    ALTER TABLE USERS ADD CONSTRAINT FK_USERS_JBGD FOREIGN KEY (JBGD_CD) REFERENCES JOB_GRADE(JBGD_CD);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_USERS_WORK_STTS') THEN
    ALTER TABLE USERS ADD CONSTRAINT FK_USERS_WORK_STTS FOREIGN KEY (WORK_STTS_CD) REFERENCES COMMON_CODE(CODE_ID);
  END IF;
END $$;

