-- StarWorks multi-tenant foundation v1
-- Apply after schema_postgres.sql and runtime_fixes_postgres.sql.

BEGIN;

CREATE TABLE IF NOT EXISTS TENANT (
    TENANT_ID VARCHAR(80) NOT NULL,
    TENANT_NM VARCHAR(200) NOT NULL,
    TENANT_SLUG VARCHAR(120) NOT NULL,
    STATUS_CD VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    OWNER_USER_ID VARCHAR(80),
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_CHG_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TENANT PRIMARY KEY (TENANT_ID)
);

CREATE TABLE IF NOT EXISTS TENANT_MEMBER (
    TENANT_ID VARCHAR(80) NOT NULL,
    USER_ID VARCHAR(80) NOT NULL,
    TENANT_ROLE_CD VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    MEMBERSHIP_STATUS_CD VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_CHG_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TENANT_MEMBER PRIMARY KEY (TENANT_ID, USER_ID)
);

CREATE TABLE IF NOT EXISTS TENANT_INVITATION (
    INVITATION_ID VARCHAR(80) NOT NULL,
    TENANT_ID VARCHAR(80) NOT NULL,
    INVITE_EMAIL VARCHAR(255) NOT NULL,
    INVITE_NAME VARCHAR(200) NOT NULL,
    TENANT_ROLE_CD VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    STATUS_CD VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    INVITATION_TOKEN VARCHAR(120) NOT NULL,
    CREATED_BY_USER_ID VARCHAR(80),
    ACCEPTED_USER_ID VARCHAR(80),
    EXPIRES_AT TIMESTAMP,
    ACCEPTED_AT TIMESTAMP,
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_CHG_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TENANT_INVITATION PRIMARY KEY (INVITATION_ID)
);

ALTER TABLE USERS ADD COLUMN IF NOT EXISTS TENANT_ID VARCHAR(80);
ALTER TABLE USERS ADD COLUMN IF NOT EXISTS LOGIN_ID VARCHAR(120);
ALTER TABLE DEPARTMENT ADD COLUMN IF NOT EXISTS TENANT_ID VARCHAR(80);
ALTER TABLE IF EXISTS COMMUNITY ADD COLUMN IF NOT EXISTS TENANT_ID VARCHAR(80);
ALTER TABLE CONTRACT_COMPANY_SETTING ADD COLUMN IF NOT EXISTS TENANT_ID VARCHAR(80);

INSERT INTO TENANT (
    TENANT_ID,
    TENANT_NM,
    TENANT_SLUG,
    STATUS_CD,
    OWNER_USER_ID,
    CRT_DT,
    LAST_CHG_DT
)
SELECT
    'TNT_DEFAULT',
    COALESCE(
        (
            SELECT COMPANY_NM
            FROM CONTRACT_COMPANY_SETTING
            ORDER BY SETTING_ID
            LIMIT 1
        ),
        'Default Workspace'
    ),
    'default',
    'ACTIVE',
    (
        SELECT USER_ID
        FROM USERS
        ORDER BY
            CASE WHEN COALESCE(USER_ROLE, '') ILIKE '%ADMIN%' THEN 0 ELSE 1 END,
            USER_ID
        LIMIT 1
    ),
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1
    FROM TENANT
    WHERE TENANT_ID = 'TNT_DEFAULT'
);

UPDATE USERS u
SET TENANT_ID = COALESCE(u.TENANT_ID, 'TNT_DEFAULT'),
    LOGIN_ID = COALESCE(
        NULLIF(u.LOGIN_ID, ''),
        src.LOGIN_ID
    )
FROM (
    SELECT
        USER_ID,
        CASE
            WHEN COALESCE(NULLIF(BTRIM(USER_EMAIL), ''), '') <> ''
                AND COUNT(*) OVER (PARTITION BY LOWER(BTRIM(USER_EMAIL))) = 1
            THEN LOWER(BTRIM(USER_EMAIL))
            ELSE LOWER(BTRIM(COALESCE(NULLIF(USER_ID, ''), USER_EMAIL)))
        END AS LOGIN_ID
    FROM USERS
) src
WHERE u.USER_ID = src.USER_ID;

UPDATE DEPARTMENT
SET TENANT_ID = COALESCE(TENANT_ID, 'TNT_DEFAULT');

UPDATE CONTRACT_COMPANY_SETTING
SET TENANT_ID = COALESCE(TENANT_ID, 'TNT_DEFAULT');

UPDATE COMMUNITY
SET TENANT_ID = COALESCE(TENANT_ID, 'TNT_DEFAULT')
WHERE EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = CURRENT_SCHEMA()
      AND table_name = 'community'
);

INSERT INTO TENANT_MEMBER (
    TENANT_ID,
    USER_ID,
    TENANT_ROLE_CD,
    MEMBERSHIP_STATUS_CD,
    CRT_DT,
    LAST_CHG_DT
)
SELECT
    COALESCE(u.TENANT_ID, 'TNT_DEFAULT'),
    u.USER_ID,
    CASE
        WHEN u.USER_ID = (
            SELECT OWNER_USER_ID
            FROM TENANT
            WHERE TENANT_ID = COALESCE(u.TENANT_ID, 'TNT_DEFAULT')
        ) THEN 'OWNER'
        WHEN COALESCE(u.USER_ROLE, '') ILIKE '%ADMIN%' THEN 'ADMIN'
        ELSE 'MEMBER'
    END,
    CASE
        WHEN COALESCE(u.RSGNTN_YN, 'N') = 'Y' THEN 'INACTIVE'
        ELSE 'ACTIVE'
    END,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM USERS u
WHERE NOT EXISTS (
    SELECT 1
    FROM TENANT_MEMBER tm
    WHERE tm.TENANT_ID = COALESCE(u.TENANT_ID, 'TNT_DEFAULT')
      AND tm.USER_ID = u.USER_ID
);

ALTER TABLE USERS ALTER COLUMN TENANT_ID SET NOT NULL;
ALTER TABLE USERS ALTER COLUMN LOGIN_ID SET NOT NULL;
ALTER TABLE DEPARTMENT ALTER COLUMN TENANT_ID SET NOT NULL;
ALTER TABLE CONTRACT_COMPANY_SETTING ALTER COLUMN TENANT_ID SET NOT NULL;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = CURRENT_SCHEMA()
          AND table_name = 'community'
    ) THEN
        EXECUTE 'ALTER TABLE COMMUNITY ALTER COLUMN TENANT_ID SET NOT NULL';
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS UQ_TENANT_SLUG ON TENANT (TENANT_SLUG);
CREATE UNIQUE INDEX IF NOT EXISTS UQ_TENANT_INVITATION_TOKEN ON TENANT_INVITATION (INVITATION_TOKEN);
CREATE UNIQUE INDEX IF NOT EXISTS UQ_USERS_TENANT_LOGIN_ID ON USERS (TENANT_ID, LOGIN_ID);
CREATE UNIQUE INDEX IF NOT EXISTS UQ_CONTRACT_COMPANY_SETTING_TENANT ON CONTRACT_COMPANY_SETTING (TENANT_ID);

CREATE INDEX IF NOT EXISTS IDX_TENANT_MEMBER_USER_ID ON TENANT_MEMBER (USER_ID, MEMBERSHIP_STATUS_CD);
CREATE INDEX IF NOT EXISTS IDX_TENANT_INVITATION_TENANT_ID ON TENANT_INVITATION (TENANT_ID, STATUS_CD, EXPIRES_AT);
CREATE INDEX IF NOT EXISTS IDX_USERS_TENANT_ID ON USERS (TENANT_ID, DEPT_ID, USER_ID);
CREATE INDEX IF NOT EXISTS IDX_DEPARTMENT_TENANT_ID ON DEPARTMENT (TENANT_ID, UP_DEPT_ID, DEPT_ID);
CREATE INDEX IF NOT EXISTS IDX_CONTRACT_COMPANY_SETTING_TENANT_ID ON CONTRACT_COMPANY_SETTING (TENANT_ID);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_USERS_TENANT') THEN
        ALTER TABLE USERS
            ADD CONSTRAINT FK_USERS_TENANT
            FOREIGN KEY (TENANT_ID) REFERENCES TENANT (TENANT_ID);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_DEPARTMENT_TENANT') THEN
        ALTER TABLE DEPARTMENT
            ADD CONSTRAINT FK_DEPARTMENT_TENANT
            FOREIGN KEY (TENANT_ID) REFERENCES TENANT (TENANT_ID);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_CONTRACT_COMPANY_SETTING_TENANT') THEN
        ALTER TABLE CONTRACT_COMPANY_SETTING
            ADD CONSTRAINT FK_CONTRACT_COMPANY_SETTING_TENANT
            FOREIGN KEY (TENANT_ID) REFERENCES TENANT (TENANT_ID);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_TENANT_OWNER_USER') THEN
        ALTER TABLE TENANT
            ADD CONSTRAINT FK_TENANT_OWNER_USER
            FOREIGN KEY (OWNER_USER_ID) REFERENCES USERS (USER_ID);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_TENANT_MEMBER_TENANT') THEN
        ALTER TABLE TENANT_MEMBER
            ADD CONSTRAINT FK_TENANT_MEMBER_TENANT
            FOREIGN KEY (TENANT_ID) REFERENCES TENANT (TENANT_ID) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_TENANT_MEMBER_USER') THEN
        ALTER TABLE TENANT_MEMBER
            ADD CONSTRAINT FK_TENANT_MEMBER_USER
            FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_TENANT_INVITATION_TENANT') THEN
        ALTER TABLE TENANT_INVITATION
            ADD CONSTRAINT FK_TENANT_INVITATION_TENANT
            FOREIGN KEY (TENANT_ID) REFERENCES TENANT (TENANT_ID) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_TENANT_INVITATION_CREATED_BY') THEN
        ALTER TABLE TENANT_INVITATION
            ADD CONSTRAINT FK_TENANT_INVITATION_CREATED_BY
            FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES USERS (USER_ID);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_TENANT_INVITATION_ACCEPTED_BY') THEN
        ALTER TABLE TENANT_INVITATION
            ADD CONSTRAINT FK_TENANT_INVITATION_ACCEPTED_BY
            FOREIGN KEY (ACCEPTED_USER_ID) REFERENCES USERS (USER_ID);
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = CURRENT_SCHEMA()
          AND table_name = 'community'
    ) AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_COMMUNITY_TENANT') THEN
        ALTER TABLE COMMUNITY
            ADD CONSTRAINT FK_COMMUNITY_TENANT
            FOREIGN KEY (TENANT_ID) REFERENCES TENANT (TENANT_ID);
    END IF;
END $$;

COMMIT;
