DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_name = 'messenger_room'
    ) THEN
        ALTER TABLE messenger_room
            ADD COLUMN IF NOT EXISTS room_type_cd VARCHAR(20) NOT NULL DEFAULT 'group',
            ADD COLUMN IF NOT EXISTS pinned_msg_cont_id VARCHAR(80),
            ADD COLUMN IF NOT EXISTS pinned_by VARCHAR(80),
            ADD COLUMN IF NOT EXISTS pinned_dt TIMESTAMP;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_name = 'messenger_user'
    ) THEN
        ALTER TABLE messenger_user
            ADD COLUMN IF NOT EXISTS role_cd VARCHAR(20) NOT NULL DEFAULT 'member',
            ADD COLUMN IF NOT EXISTS notify_yn CHAR(1) NOT NULL DEFAULT 'Y';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_name = 'messenger_content'
    ) THEN
        ALTER TABLE messenger_content
            ADD COLUMN IF NOT EXISTS msg_type_cd VARCHAR(20) NOT NULL DEFAULT 'text',
            ADD COLUMN IF NOT EXISTS forward_from_msg_cont_id VARCHAR(80);
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_name = 'messenger_user'
    ) AND NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uk_messenger_user_room_member'
    ) THEN
        DELETE FROM messenger_user a
        USING messenger_user b
        WHERE a.ctid < b.ctid
          AND a.msgr_id = b.msgr_id
          AND a.user_id = b.user_id;

        ALTER TABLE messenger_user
            ADD CONSTRAINT uk_messenger_user_room_member UNIQUE (msgr_id, user_id);
    END IF;
END $$;

DO $$
DECLARE
    current_key_columns text[];
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'time_and_attendance'
          AND column_name = 'work_ymd'
    ) THEN
        UPDATE time_and_attendance
        SET work_ymd = date_trunc('day', COALESCE(work_bgng_dt, work_end_dt, CURRENT_TIMESTAMP))
        WHERE work_ymd IS NULL;

        SELECT array_agg(a.attname ORDER BY key_columns.ordinality)
        INTO current_key_columns
        FROM pg_constraint c
        JOIN pg_class t
          ON t.oid = c.conrelid
        JOIN pg_namespace n
          ON n.oid = t.relnamespace
        JOIN LATERAL unnest(c.conkey) WITH ORDINALITY AS key_columns(attnum, ordinality)
          ON true
        JOIN pg_attribute a
          ON a.attrelid = t.oid
         AND a.attnum = key_columns.attnum
        WHERE c.contype = 'p'
          AND n.nspname = 'public'
          AND t.relname = 'time_and_attendance';

        IF current_key_columns IS DISTINCT FROM ARRAY['user_id', 'work_ymd'] THEN
            IF EXISTS (
                SELECT 1
                FROM pg_constraint c
                JOIN pg_class t
                  ON t.oid = c.conrelid
                JOIN pg_namespace n
                  ON n.oid = t.relnamespace
                WHERE c.contype = 'p'
                  AND n.nspname = 'public'
                  AND t.relname = 'time_and_attendance'
            ) THEN
                ALTER TABLE time_and_attendance DROP CONSTRAINT pk_time_and_attendance;
            END IF;

            ALTER TABLE time_and_attendance
                ALTER COLUMN work_ymd SET NOT NULL;

            ALTER TABLE time_and_attendance
                ADD CONSTRAINT pk_time_and_attendance PRIMARY KEY (user_id, work_ymd);
        END IF;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS COMMUNITY (
    COMMUNITY_ID BIGSERIAL PRIMARY KEY,
    COMMUNITY_NM VARCHAR(120) NOT NULL,
    COMMUNITY_DESC TEXT,
    COMMUNITY_TYPE_CD VARCHAR(20) NOT NULL DEFAULT 'general',
    OWNER_USER_ID VARCHAR(80) REFERENCES USERS(USER_ID) ON DELETE RESTRICT,
    DEL_YN CHAR(1) NOT NULL DEFAULT 'N',
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_CHG_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS COMMUNITY_MEMBER (
    COMMUNITY_ID BIGINT NOT NULL REFERENCES COMMUNITY(COMMUNITY_ID) ON DELETE CASCADE,
    USER_ID VARCHAR(80) NOT NULL REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    ROLE_CD VARCHAR(20) NOT NULL DEFAULT 'member',
    STATUS_CD VARCHAR(20) NOT NULL DEFAULT 'active',
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_CHG_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (COMMUNITY_ID, USER_ID)
);

ALTER TABLE COMMUNITY
    ADD COLUMN IF NOT EXISTS VISIBILITY_CD VARCHAR(20) NOT NULL DEFAULT 'private',
    ADD COLUMN IF NOT EXISTS JOIN_POLICY_CD VARCHAR(20) NOT NULL DEFAULT 'invite_only',
    ADD COLUMN IF NOT EXISTS DEPT_ID VARCHAR(80),
    ADD COLUMN IF NOT EXISTS INTRO_TEXT TEXT,
    ADD COLUMN IF NOT EXISTS ICON_FILE_ID VARCHAR(80),
    ADD COLUMN IF NOT EXISTS COVER_FILE_ID VARCHAR(80),
    ADD COLUMN IF NOT EXISTS POST_TEMPLATE_HTML TEXT,
    ADD COLUMN IF NOT EXISTS CLOSED_YN CHAR(1) NOT NULL DEFAULT 'N',
    ADD COLUMN IF NOT EXISTS CLOSED_DT TIMESTAMP;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'community'
          AND column_name = 'owner_user_id'
          AND is_nullable = 'NO'
    ) THEN
        ALTER TABLE COMMUNITY ALTER COLUMN OWNER_USER_ID DROP NOT NULL;
    END IF;
END $$;

UPDATE COMMUNITY
SET COMMUNITY_TYPE_CD = CASE
    WHEN COALESCE(COMMUNITY_TYPE_CD, 'general') = 'group' THEN 'general'
    ELSE COALESCE(COMMUNITY_TYPE_CD, 'general')
END;

UPDATE COMMUNITY
SET VISIBILITY_CD = CASE
        WHEN COALESCE(COMMUNITY_TYPE_CD, 'general') = 'org' THEN 'org'
        ELSE COALESCE(VISIBILITY_CD, 'private')
    END,
    JOIN_POLICY_CD = CASE
        WHEN COALESCE(COMMUNITY_TYPE_CD, 'general') = 'org' THEN 'auto'
        ELSE COALESCE(JOIN_POLICY_CD, 'invite_only')
    END,
    INTRO_TEXT = COALESCE(INTRO_TEXT, COMMUNITY_DESC),
    CLOSED_YN = COALESCE(CLOSED_YN, 'N');

CREATE TABLE IF NOT EXISTS COMMUNITY_USER_PREF (
    COMMUNITY_ID BIGINT NOT NULL REFERENCES COMMUNITY(COMMUNITY_ID) ON DELETE CASCADE,
    USER_ID VARCHAR(80) NOT NULL REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    FAVORITE_YN CHAR(1) NOT NULL DEFAULT 'N',
    SORT_ORDR INTEGER NOT NULL DEFAULT 9999,
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_CHG_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (COMMUNITY_ID, USER_ID)
);

CREATE INDEX IF NOT EXISTS IDX_COMMUNITY_OWNER ON COMMUNITY (OWNER_USER_ID, DEL_YN, CRT_DT DESC);
CREATE INDEX IF NOT EXISTS IDX_COMMUNITY_MEMBER_USER ON COMMUNITY_MEMBER (USER_ID, STATUS_CD, COMMUNITY_ID);
CREATE INDEX IF NOT EXISTS IDX_COMMUNITY_TYPE_VISIBILITY ON COMMUNITY (COMMUNITY_TYPE_CD, VISIBILITY_CD, DEL_YN, CLOSED_YN);
CREATE INDEX IF NOT EXISTS IDX_COMMUNITY_DEPT ON COMMUNITY (DEPT_ID, COMMUNITY_TYPE_CD);
CREATE INDEX IF NOT EXISTS IDX_COMMUNITY_PREF_USER ON COMMUNITY_USER_PREF (USER_ID, FAVORITE_YN, SORT_ORDR, COMMUNITY_ID);
CREATE INDEX IF NOT EXISTS IDX_MESSENGER_CONTENT_ROOM_TYPE ON MESSENGER_CONTENT (MSGR_ID, MSG_TYPE_CD, SEND_DT DESC);
CREATE INDEX IF NOT EXISTS IDX_MESSENGER_USER_NOTIFY ON MESSENGER_USER (USER_ID, NOTIFY_YN, LEFT_DT);

CREATE UNIQUE INDEX IF NOT EXISTS UK_COMMUNITY_ORG_DEPT
    ON COMMUNITY (DEPT_ID)
    WHERE COMMUNITY_TYPE_CD = 'org' AND DEPT_ID IS NOT NULL;

UPDATE COMMUNITY_MEMBER cm
SET ROLE_CD = 'owner',
    STATUS_CD = 'active',
    LAST_CHG_DT = CURRENT_TIMESTAMP
FROM COMMUNITY c
WHERE cm.COMMUNITY_ID = c.COMMUNITY_ID
  AND cm.USER_ID = c.OWNER_USER_ID
  AND COALESCE(c.DEL_YN, 'N') = 'N'
  AND (cm.ROLE_CD IS DISTINCT FROM 'owner' OR cm.STATUS_CD IS DISTINCT FROM 'active');

INSERT INTO COMMUNITY_USER_PREF (COMMUNITY_ID, USER_ID, FAVORITE_YN, SORT_ORDR, CRT_DT, LAST_CHG_DT)
SELECT
    cm.community_id,
    cm.user_id,
    'N',
    ROW_NUMBER() OVER (PARTITION BY cm.user_id ORDER BY c.community_nm, c.community_id),
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM COMMUNITY_MEMBER cm
JOIN COMMUNITY c
  ON c.community_id = cm.community_id
WHERE cm.status_cd = 'active'
  AND COALESCE(c.del_yn, 'N') = 'N'
ON CONFLICT (COMMUNITY_ID, USER_ID) DO NOTHING;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'meeting_room'
          AND column_name = 'capacity'
          AND data_type <> 'integer'
    ) THEN
        ALTER TABLE meeting_room
            ALTER COLUMN capacity TYPE integer
            USING NULLIF(capacity, '')::integer;
    END IF;
END $$;

ALTER TABLE BOARD
    ALTER COLUMN FRST_CRT_DT SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE BOARD
    ALTER COLUMN LAST_CHG_DT SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE BOARD
    ALTER COLUMN VIEW_CNT SET DEFAULT 0;

ALTER TABLE BOARD
    ADD COLUMN IF NOT EXISTS COMMUNITY_ID BIGINT,
    ADD COLUMN IF NOT EXISTS COMMUNITY_AUTHOR_ROLE_CD VARCHAR(20) DEFAULT 'member',
    ADD COLUMN IF NOT EXISTS IMPORTANCE_CD VARCHAR(20) DEFAULT 'normal',
    ADD COLUMN IF NOT EXISTS LINK_URL VARCHAR(500),
    ADD COLUMN IF NOT EXISTS PST_TYPE_CD VARCHAR(20) DEFAULT 'story',
    ADD COLUMN IF NOT EXISTS PUBLISHED_DT TIMESTAMP,
    ADD COLUMN IF NOT EXISTS PUBLISH_STATE_CD VARCHAR(20) DEFAULT 'published',
    ADD COLUMN IF NOT EXISTS RESERVED_PUBLISH_DT TIMESTAMP,
    ADD COLUMN IF NOT EXISTS VISIBILITY_CD VARCHAR(20) DEFAULT 'community';

UPDATE BOARD
SET FRST_CRT_DT = CURRENT_TIMESTAMP
WHERE FRST_CRT_DT IS NULL;

UPDATE BOARD
SET VIEW_CNT = 0
WHERE VIEW_CNT IS NULL;

UPDATE BOARD
SET PST_TYPE_CD = 'story'
WHERE PST_TYPE_CD IS NULL;

UPDATE BOARD
SET VISIBILITY_CD = 'community'
WHERE VISIBILITY_CD IS NULL;

UPDATE BOARD
SET PUBLISH_STATE_CD = CASE
    WHEN RESERVED_PUBLISH_DT IS NOT NULL AND RESERVED_PUBLISH_DT > CURRENT_TIMESTAMP THEN 'scheduled'
    ELSE 'published'
END
WHERE PUBLISH_STATE_CD IS NULL;

UPDATE BOARD
SET PUBLISHED_DT = COALESCE(PUBLISHED_DT, FRST_CRT_DT, CURRENT_TIMESTAMP)
WHERE PUBLISH_STATE_CD = 'published'
  AND PUBLISHED_DT IS NULL;

UPDATE BOARD
SET IMPORTANCE_CD = CASE
    WHEN BBS_CTGR_CD = 'F101' OR COALESCE(FIXED_YN, 'N') = 'Y' THEN 'notice'
    ELSE 'normal'
END
WHERE IMPORTANCE_CD IS NULL;

UPDATE BOARD B
SET COMMUNITY_AUTHOR_ROLE_CD = CASE
    WHEN EXISTS (
        SELECT 1
        FROM COMMUNITY C
        WHERE C.COMMUNITY_ID = B.COMMUNITY_ID
          AND C.OWNER_USER_ID = B.CRT_USER_ID
    ) THEN 'owner'
    ELSE COALESCE(B.COMMUNITY_AUTHOR_ROLE_CD, 'member')
END
WHERE B.COMMUNITY_ID IS NOT NULL
  AND (B.COMMUNITY_AUTHOR_ROLE_CD IS NULL OR B.COMMUNITY_AUTHOR_ROLE_CD = '');

ALTER TABLE BOARD_COMMENT
    ALTER COLUMN FRST_CRT_DT SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE BOARD_COMMENT
    ALTER COLUMN LAST_CHG_DT SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE BOARD_COMMENT
    ADD COLUMN IF NOT EXISTS CMNT_FILE_ID VARCHAR(80);

UPDATE BOARD_COMMENT
SET FRST_CRT_DT = CURRENT_TIMESTAMP
WHERE FRST_CRT_DT IS NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uk_board_pst_id'
    ) AND NOT EXISTS (
        SELECT 1
        FROM board
        WHERE pst_id IS NULL
    ) AND NOT EXISTS (
        SELECT 1
        FROM board
        GROUP BY pst_id
        HAVING COUNT(*) > 1
    ) THEN
        ALTER TABLE board
            ADD CONSTRAINT uk_board_pst_id UNIQUE (pst_id);
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_name = 'community'
    ) THEN
        ALTER TABLE BOARD
            ADD CONSTRAINT fk_board_community
            FOREIGN KEY (community_id)
            REFERENCES COMMUNITY (community_id)
            ON DELETE SET NULL;
    END IF;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS BOARD_POLL (
    PST_ID VARCHAR(80) PRIMARY KEY REFERENCES BOARD(PST_ID) ON DELETE CASCADE,
    ANONYMOUS_YN CHAR(1) NOT NULL DEFAULT 'N',
    DEADLINE_DT TIMESTAMP,
    MULTIPLE_YN CHAR(1) NOT NULL DEFAULT 'N',
    PARTICIPANT_OPEN_YN CHAR(1) NOT NULL DEFAULT 'Y',
    RESULT_OPEN_YN CHAR(1) NOT NULL DEFAULT 'Y'
);

CREATE TABLE IF NOT EXISTS BOARD_POLL_OPTION (
    OPTION_ID BIGSERIAL PRIMARY KEY,
    PST_ID VARCHAR(80) NOT NULL REFERENCES BOARD(PST_ID) ON DELETE CASCADE,
    OPTION_TEXT VARCHAR(255) NOT NULL,
    SORT_ORDR INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS BOARD_POLL_RESPONSE (
    RESPONSE_ID BIGSERIAL PRIMARY KEY,
    PST_ID VARCHAR(80) NOT NULL REFERENCES BOARD(PST_ID) ON DELETE CASCADE,
    OPTION_ID BIGINT NOT NULL REFERENCES BOARD_POLL_OPTION(OPTION_ID) ON DELETE CASCADE,
    USER_ID VARCHAR(80) NOT NULL REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (PST_ID, OPTION_ID, USER_ID)
);

CREATE TABLE IF NOT EXISTS BOARD_SCHEDULE (
    PST_ID VARCHAR(80) PRIMARY KEY REFERENCES BOARD(PST_ID) ON DELETE CASCADE,
    START_DT TIMESTAMP NOT NULL,
    END_DT TIMESTAMP NOT NULL,
    ALLDAY_YN CHAR(1) NOT NULL DEFAULT 'N',
    REPEAT_RULE VARCHAR(255),
    PLACE_TEXT VARCHAR(255),
    PLACE_URL VARCHAR(500),
    REMINDER_MINUTES INTEGER,
    VIDEO_MEETING_YN CHAR(1) NOT NULL DEFAULT 'N',
    MEETING_ROOM_ID VARCHAR(80),
    MEETING_RESERVATION_ID INTEGER
);

CREATE TABLE IF NOT EXISTS BOARD_SCHEDULE_ATTENDEE (
    PST_ID VARCHAR(80) NOT NULL REFERENCES BOARD(PST_ID) ON DELETE CASCADE,
    USER_ID VARCHAR(80) NOT NULL REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    ATTENDANCE_STTS_CD VARCHAR(20) NOT NULL DEFAULT 'invited',
    PRIMARY KEY (PST_ID, USER_ID)
);

CREATE TABLE IF NOT EXISTS BOARD_TODO (
    PST_ID VARCHAR(80) PRIMARY KEY REFERENCES BOARD(PST_ID) ON DELETE CASCADE,
    DUE_DT TIMESTAMP,
    STATUS_CD VARCHAR(20) NOT NULL DEFAULT 'requested'
);

CREATE TABLE IF NOT EXISTS BOARD_TODO_ASSIGNEE (
    PST_ID VARCHAR(80) NOT NULL REFERENCES BOARD(PST_ID) ON DELETE CASCADE,
    USER_ID VARCHAR(80) NOT NULL REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    STATUS_CD VARCHAR(20) NOT NULL DEFAULT 'requested',
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_CHG_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (PST_ID, USER_ID)
);

CREATE TABLE IF NOT EXISTS BOARD_POST_REACTION (
    PST_ID VARCHAR(80) NOT NULL REFERENCES BOARD(PST_ID) ON DELETE CASCADE,
    USER_ID VARCHAR(80) NOT NULL REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    REACTION_CD VARCHAR(20) NOT NULL DEFAULT 'like',
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (PST_ID, USER_ID, REACTION_CD)
);

CREATE TABLE IF NOT EXISTS BOARD_POST_MENTION (
    PST_ID VARCHAR(80) NOT NULL REFERENCES BOARD(PST_ID) ON DELETE CASCADE,
    USER_ID VARCHAR(80) NOT NULL REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (PST_ID, USER_ID)
);

CREATE TABLE IF NOT EXISTS BOARD_COMMENT_MENTION (
    CMNT_SQN VARCHAR(255) NOT NULL,
    USER_ID VARCHAR(80) NOT NULL REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (CMNT_SQN, USER_ID)
);

CREATE TABLE IF NOT EXISTS BOARD_REPORT (
    REPORT_ID BIGSERIAL PRIMARY KEY,
    PST_ID VARCHAR(80) NOT NULL REFERENCES BOARD(PST_ID) ON DELETE CASCADE,
    REPORTER_ID VARCHAR(80) NOT NULL REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    REASON_TEXT VARCHAR(500) NOT NULL,
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STATUS_CD VARCHAR(20) NOT NULL DEFAULT 'submitted',
    UNIQUE (PST_ID, REPORTER_ID)
);

CREATE TABLE IF NOT EXISTS BOARD_SHARE (
    SHARE_ID BIGSERIAL PRIMARY KEY,
    PST_ID VARCHAR(80) NOT NULL REFERENCES BOARD(PST_ID) ON DELETE CASCADE,
    SHARE_TYPE_CD VARCHAR(20) NOT NULL,
    SHARE_TARGET_ID VARCHAR(80) NOT NULL,
    SHARE_USER_ID VARCHAR(80) NOT NULL REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS BOARD_SHARE_RECIPIENT (
    SHARE_ID BIGINT NOT NULL REFERENCES BOARD_SHARE(SHARE_ID) ON DELETE CASCADE,
    PST_ID VARCHAR(80) NOT NULL REFERENCES BOARD(PST_ID) ON DELETE CASCADE,
    RECIPIENT_USER_ID VARCHAR(80) NOT NULL REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (SHARE_ID, RECIPIENT_USER_ID)
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uk_board_share_recipient_post_user'
    ) THEN
        ALTER TABLE BOARD_SHARE_RECIPIENT
            ADD CONSTRAINT uk_board_share_recipient_post_user UNIQUE (PST_ID, RECIPIENT_USER_ID);
    END IF;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

CREATE SEQUENCE IF NOT EXISTS CONTRACT_SETTING_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS CONTRACT_REQ_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS CONTRACT_TMPL_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS CONTRACT_TMPL_VER_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS CONTRACT_BATCH_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS CONTRACT_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS CONTRACT_SIGNER_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS CONTRACT_INVITATION_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS CONTRACT_FIELD_VALUE_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS CONTRACT_AUDIT_ID_SEQ;

CREATE TABLE IF NOT EXISTS CONTRACT_COMPANY_SETTING (
    SETTING_ID BIGINT NOT NULL DEFAULT nextval('CONTRACT_SETTING_ID_SEQ'),
    COMPANY_NM VARCHAR(200),
    SENDER_NM VARCHAR(120),
    SENDER_EMAIL VARCHAR(255),
    SENDER_TELNO VARCHAR(30),
    SEAL_FILE_ID VARCHAR(80),
    PROVIDER_NM VARCHAR(80),
    ADMIN_READY_YN CHAR(1) DEFAULT 'N',
    GUIDE_ACK_YN CHAR(1) DEFAULT 'N',
    CHECKLIST_JSON TEXT,
    NOTE_TEXT TEXT,
    CRT_USER_ID VARCHAR(80),
    CRT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_CHG_USER_ID VARCHAR(80),
    LAST_CHG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CONTRACT_COMPANY_SETTING PRIMARY KEY (SETTING_ID)
);

CREATE TABLE IF NOT EXISTS CONTRACT_TEMPLATE_REQUEST (
    REQUEST_ID BIGINT NOT NULL DEFAULT nextval('CONTRACT_REQ_ID_SEQ'),
    REQUEST_REF VARCHAR(80),
    REQUEST_TITLE VARCHAR(200) NOT NULL,
    REQUEST_STATUS_CD VARCHAR(20) NOT NULL DEFAULT 'requested',
    REQUEST_NOTE TEXT,
    REQUESTER_USER_ID VARCHAR(80),
    REVIEW_USER_ID VARCHAR(80),
    REVIEW_NOTE TEXT,
    SOURCE_FILE_ID VARCHAR(80),
    MARKED_FILE_ID VARCHAR(80),
    SEAL_FILE_ID VARCHAR(80),
    CONVERTED_TEMPLATE_ID BIGINT,
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    REVIEW_DT TIMESTAMP,
    LAST_CHG_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CONTRACT_TEMPLATE_REQUEST PRIMARY KEY (REQUEST_ID)
);

CREATE TABLE IF NOT EXISTS CONTRACT_TEMPLATE (
    TEMPLATE_ID BIGINT NOT NULL DEFAULT nextval('CONTRACT_TMPL_ID_SEQ'),
    TEMPLATE_CODE VARCHAR(80),
    TEMPLATE_NM VARCHAR(200) NOT NULL,
    TEMPLATE_DESC TEXT,
    TEMPLATE_CATEGORY_CD VARCHAR(40) NOT NULL DEFAULT 'general',
    ACTIVE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    REQUEST_ID BIGINT,
    PUBLISHED_VERSION_ID BIGINT,
    CRT_USER_ID VARCHAR(80),
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_CHG_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CONTRACT_TEMPLATE PRIMARY KEY (TEMPLATE_ID)
);

CREATE TABLE IF NOT EXISTS CONTRACT_TEMPLATE_VERSION (
    TEMPLATE_VERSION_ID BIGINT NOT NULL DEFAULT nextval('CONTRACT_TMPL_VER_ID_SEQ'),
    TEMPLATE_ID BIGINT NOT NULL REFERENCES CONTRACT_TEMPLATE(TEMPLATE_ID) ON DELETE CASCADE,
    VERSION_NO INTEGER NOT NULL,
    VERSION_LABEL VARCHAR(120),
    VERSION_STATUS_CD VARCHAR(20) NOT NULL DEFAULT 'draft',
    VERSION_NOTE TEXT,
    SOURCE_FILE_ID VARCHAR(80),
    BACKGROUND_FILE_ID VARCHAR(80),
    SCHEMA_JSON TEXT,
    LAYOUT_JSON TEXT,
    CRT_USER_ID VARCHAR(80),
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PUBLISHED_DT TIMESTAMP,
    LAST_CHG_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CONTRACT_TEMPLATE_VERSION PRIMARY KEY (TEMPLATE_VERSION_ID)
);

CREATE TABLE IF NOT EXISTS CONTRACT_BATCH (
    BATCH_ID BIGINT NOT NULL DEFAULT nextval('CONTRACT_BATCH_ID_SEQ'),
    BATCH_REF VARCHAR(80),
    TEMPLATE_ID BIGINT REFERENCES CONTRACT_TEMPLATE(TEMPLATE_ID) ON DELETE SET NULL,
    TEMPLATE_VERSION_ID BIGINT REFERENCES CONTRACT_TEMPLATE_VERSION(TEMPLATE_VERSION_ID) ON DELETE SET NULL,
    BATCH_TITLE VARCHAR(200) NOT NULL,
    CREATOR_USER_ID VARCHAR(80),
    TOTAL_COUNT INTEGER NOT NULL DEFAULT 0,
    SUCCESS_COUNT INTEGER NOT NULL DEFAULT 0,
    FAILED_COUNT INTEGER NOT NULL DEFAULT 0,
    RESULT_JSON TEXT,
    SOURCE_FILE_ID VARCHAR(80),
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_CHG_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CONTRACT_BATCH PRIMARY KEY (BATCH_ID)
);

CREATE TABLE IF NOT EXISTS CONTRACT_DOCUMENT (
    CONTRACT_ID BIGINT NOT NULL DEFAULT nextval('CONTRACT_ID_SEQ'),
    CONTRACT_REF VARCHAR(80),
    TEMPLATE_ID BIGINT REFERENCES CONTRACT_TEMPLATE(TEMPLATE_ID) ON DELETE SET NULL,
    TEMPLATE_VERSION_ID BIGINT REFERENCES CONTRACT_TEMPLATE_VERSION(TEMPLATE_VERSION_ID) ON DELETE SET NULL,
    BATCH_ID BIGINT REFERENCES CONTRACT_BATCH(BATCH_ID) ON DELETE SET NULL,
    CONTRACT_TITLE VARCHAR(255) NOT NULL,
    CONTRACT_MESSAGE TEXT,
    SEND_TYPE_CD VARCHAR(20) NOT NULL DEFAULT 'remote',
    SIGNING_FLOW_CD VARCHAR(20) NOT NULL DEFAULT 'parallel',
    STATUS_CD VARCHAR(20) NOT NULL DEFAULT 'draft',
    CREATOR_USER_ID VARCHAR(80),
    SENDER_NM VARCHAR(120),
    SENDER_EMAIL VARCHAR(255),
    SENDER_TELNO VARCHAR(30),
    COMPANY_SNAPSHOT_JSON TEXT,
    TEMPLATE_SCHEMA_JSON TEXT,
    TEMPLATE_LAYOUT_JSON TEXT,
    FINAL_HTML_DATA TEXT,
    FINAL_FILE_ID VARCHAR(80),
    EXPIRES_DT TIMESTAMP,
    SENT_DT TIMESTAMP,
    COMPLETED_DT TIMESTAMP,
    CANCELLED_DT TIMESTAMP,
    CANCELLED_REASON VARCHAR(500),
    TOTAL_SIGNER_COUNT INTEGER NOT NULL DEFAULT 0,
    CURRENT_SIGN_ORDER INTEGER NOT NULL DEFAULT 1,
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_CHG_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CONTRACT_DOCUMENT PRIMARY KEY (CONTRACT_ID)
);

CREATE TABLE IF NOT EXISTS CONTRACT_SIGNER (
    SIGNER_ID BIGINT NOT NULL DEFAULT nextval('CONTRACT_SIGNER_ID_SEQ'),
    CONTRACT_ID BIGINT NOT NULL REFERENCES CONTRACT_DOCUMENT(CONTRACT_ID) ON DELETE CASCADE,
    SIGNER_ORDER INTEGER NOT NULL DEFAULT 1,
    SIGNER_ROLE_CD VARCHAR(20) NOT NULL DEFAULT 'signer',
    SIGNER_TYPE_CD VARCHAR(20) NOT NULL DEFAULT 'external',
    INTERNAL_USER_ID VARCHAR(80),
    SIGNER_NM VARCHAR(120) NOT NULL,
    SIGNER_EMAIL VARCHAR(255),
    SIGNER_TELNO VARCHAR(30),
    STATUS_CD VARCHAR(20) NOT NULL DEFAULT 'pending',
    OPENED_DT TIMESTAMP,
    SIGNED_DT TIMESTAMP,
    DECLINED_REASON VARCHAR(500),
    SIGNATURE_DATA TEXT,
    INITIAL_DATA TEXT,
    CLAIMED_NM VARCHAR(120),
    CLAIMED_EMAIL VARCHAR(255),
    CLAIMED_TELNO VARCHAR(30),
    LAST_CHG_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CONTRACT_SIGNER PRIMARY KEY (SIGNER_ID)
);

CREATE TABLE IF NOT EXISTS CONTRACT_INVITATION (
    INVITATION_ID BIGINT NOT NULL DEFAULT nextval('CONTRACT_INVITATION_ID_SEQ'),
    CONTRACT_ID BIGINT NOT NULL REFERENCES CONTRACT_DOCUMENT(CONTRACT_ID) ON DELETE CASCADE,
    SIGNER_ID BIGINT NOT NULL REFERENCES CONTRACT_SIGNER(SIGNER_ID) ON DELETE CASCADE,
    TOKEN_HASH VARCHAR(255),
    TOKEN_HINT VARCHAR(24),
    CHANNEL_CD VARCHAR(20) NOT NULL DEFAULT 'remote',
    DELIVERY_STATUS_CD VARCHAR(20) NOT NULL DEFAULT 'pending',
    DELIVERY_NOTE VARCHAR(255),
    ACTIVE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    SENT_DT TIMESTAMP,
    OPENED_DT TIMESTAMP,
    COMPLETED_DT TIMESTAMP,
    EXPIRES_DT TIMESTAMP,
    LAST_CHG_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CONTRACT_INVITATION PRIMARY KEY (INVITATION_ID)
);

CREATE TABLE IF NOT EXISTS CONTRACT_FIELD_VALUE (
    FIELD_VALUE_ID BIGINT NOT NULL DEFAULT nextval('CONTRACT_FIELD_VALUE_ID_SEQ'),
    CONTRACT_ID BIGINT NOT NULL REFERENCES CONTRACT_DOCUMENT(CONTRACT_ID) ON DELETE CASCADE,
    FIELD_KEY VARCHAR(120) NOT NULL,
    REPEAT_GROUP_KEY VARCHAR(120),
    ROW_INDEX INTEGER NOT NULL DEFAULT 0,
    FIELD_VALUE TEXT,
    SIGNER_ID BIGINT REFERENCES CONTRACT_SIGNER(SIGNER_ID) ON DELETE SET NULL,
    LAST_CHG_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CONTRACT_FIELD_VALUE PRIMARY KEY (FIELD_VALUE_ID)
);

CREATE TABLE IF NOT EXISTS CONTRACT_AUDIT_LOG (
    AUDIT_ID BIGINT NOT NULL DEFAULT nextval('CONTRACT_AUDIT_ID_SEQ'),
    CONTRACT_ID BIGINT NOT NULL REFERENCES CONTRACT_DOCUMENT(CONTRACT_ID) ON DELETE CASCADE,
    SIGNER_ID BIGINT REFERENCES CONTRACT_SIGNER(SIGNER_ID) ON DELETE SET NULL,
    ACTOR_USER_ID VARCHAR(80),
    ACTOR_NM VARCHAR(120),
    ACTOR_TYPE_CD VARCHAR(20) NOT NULL DEFAULT 'system',
    ACTION_CD VARCHAR(40) NOT NULL,
    ACTION_MESSAGE VARCHAR(500),
    PAYLOAD_JSON TEXT,
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CONTRACT_AUDIT_LOG PRIMARY KEY (AUDIT_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS UK_CONTRACT_TEMPLATE_REQUEST_REF ON CONTRACT_TEMPLATE_REQUEST (REQUEST_REF);
CREATE UNIQUE INDEX IF NOT EXISTS UK_CONTRACT_TEMPLATE_CODE ON CONTRACT_TEMPLATE (TEMPLATE_CODE);
CREATE UNIQUE INDEX IF NOT EXISTS UK_CONTRACT_TEMPLATE_VERSION_NUM ON CONTRACT_TEMPLATE_VERSION (TEMPLATE_ID, VERSION_NO);
CREATE UNIQUE INDEX IF NOT EXISTS UK_CONTRACT_BATCH_REF ON CONTRACT_BATCH (BATCH_REF);
CREATE UNIQUE INDEX IF NOT EXISTS UK_CONTRACT_DOCUMENT_REF ON CONTRACT_DOCUMENT (CONTRACT_REF);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contract_template_request') THEN
        ALTER TABLE CONTRACT_TEMPLATE
            ADD CONSTRAINT fk_contract_template_request
            FOREIGN KEY (REQUEST_ID)
            REFERENCES CONTRACT_TEMPLATE_REQUEST (REQUEST_ID)
            ON DELETE SET NULL;
    END IF;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contract_template_request_converted') THEN
        ALTER TABLE CONTRACT_TEMPLATE_REQUEST
            ADD CONSTRAINT fk_contract_template_request_converted
            FOREIGN KEY (CONVERTED_TEMPLATE_ID)
            REFERENCES CONTRACT_TEMPLATE (TEMPLATE_ID)
            ON DELETE SET NULL;
    END IF;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contract_template_published_version') THEN
        ALTER TABLE CONTRACT_TEMPLATE
            ADD CONSTRAINT fk_contract_template_published_version
            FOREIGN KEY (PUBLISHED_VERSION_ID)
            REFERENCES CONTRACT_TEMPLATE_VERSION (TEMPLATE_VERSION_ID)
            ON DELETE SET NULL;
    END IF;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS IDX_CONTRACT_TEMPLATE_ACTIVE ON CONTRACT_TEMPLATE (ACTIVE_YN, TEMPLATE_CATEGORY_CD, TEMPLATE_NM);
CREATE INDEX IF NOT EXISTS IDX_CONTRACT_TEMPLATE_VERSION_STATUS ON CONTRACT_TEMPLATE_VERSION (TEMPLATE_ID, VERSION_STATUS_CD, VERSION_NO DESC);
CREATE INDEX IF NOT EXISTS IDX_CONTRACT_DOCUMENT_STATUS ON CONTRACT_DOCUMENT (STATUS_CD, CRT_DT DESC);
CREATE INDEX IF NOT EXISTS IDX_CONTRACT_DOCUMENT_CREATOR ON CONTRACT_DOCUMENT (CREATOR_USER_ID, CRT_DT DESC);
CREATE INDEX IF NOT EXISTS IDX_CONTRACT_DOCUMENT_TEMPLATE ON CONTRACT_DOCUMENT (TEMPLATE_ID, TEMPLATE_VERSION_ID);
CREATE INDEX IF NOT EXISTS IDX_CONTRACT_DOCUMENT_BATCH ON CONTRACT_DOCUMENT (BATCH_ID, CRT_DT DESC);
CREATE INDEX IF NOT EXISTS IDX_CONTRACT_SIGNER_CONTRACT ON CONTRACT_SIGNER (CONTRACT_ID, SIGNER_ORDER);
CREATE INDEX IF NOT EXISTS IDX_CONTRACT_SIGNER_INTERNAL_USER ON CONTRACT_SIGNER (INTERNAL_USER_ID, STATUS_CD, SIGNED_DT DESC);
CREATE INDEX IF NOT EXISTS IDX_CONTRACT_INVITATION_TOKEN_HASH ON CONTRACT_INVITATION (TOKEN_HASH);
CREATE INDEX IF NOT EXISTS IDX_CONTRACT_INVITATION_SIGNER ON CONTRACT_INVITATION (SIGNER_ID, ACTIVE_YN, EXPIRES_DT);
CREATE INDEX IF NOT EXISTS IDX_CONTRACT_FIELD_VALUE_CONTRACT ON CONTRACT_FIELD_VALUE (CONTRACT_ID, FIELD_KEY, ROW_INDEX);
CREATE INDEX IF NOT EXISTS IDX_CONTRACT_AUDIT_LOG_CONTRACT ON CONTRACT_AUDIT_LOG (CONTRACT_ID, CRT_DT DESC);
CREATE INDEX IF NOT EXISTS IDX_CONTRACT_TEMPLATE_REQUEST_STATUS ON CONTRACT_TEMPLATE_REQUEST (REQUEST_STATUS_CD, CRT_DT DESC);

CREATE TABLE IF NOT EXISTS USER_FEED_PREFERENCE (
    USER_ID VARCHAR(80) PRIMARY KEY REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    DEFAULT_SCOPE VARCHAR(40) NOT NULL DEFAULT 'all',
    DEFAULT_SORT VARCHAR(20) NOT NULL DEFAULT 'recent',
    DEFAULT_VIEW VARCHAR(20) NOT NULL DEFAULT 'summary',
    DEFAULT_CATEGORY VARCHAR(20) NOT NULL DEFAULT 'all',
    LAST_DEPT_ID VARCHAR(80) REFERENCES DEPARTMENT(DEPT_ID) ON DELETE SET NULL,
    LAST_SEARCH_Q VARCHAR(255),
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_CHG_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS USER_FEED_CATEGORY (
    USER_ID VARCHAR(80) NOT NULL REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    BBS_CTGR_CD VARCHAR(20) NOT NULL,
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID, BBS_CTGR_CD)
);

CREATE TABLE IF NOT EXISTS USER_FEED_READ (
    USER_ID VARCHAR(80) NOT NULL REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    PST_ID VARCHAR(80) NOT NULL,
    READ_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID, PST_ID)
);

CREATE TABLE IF NOT EXISTS USER_SAVED_POST (
    USER_ID VARCHAR(80) NOT NULL REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    PST_ID VARCHAR(80) NOT NULL,
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID, PST_ID)
);

CREATE TABLE IF NOT EXISTS USER_FAVORITE_USER (
    USER_ID VARCHAR(80) NOT NULL REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    TARGET_USER_ID VARCHAR(80) NOT NULL REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID, TARGET_USER_ID)
);

CREATE TABLE IF NOT EXISTS USER_TODO (
    TODO_ID BIGSERIAL PRIMARY KEY,
    USER_ID VARCHAR(80) NOT NULL REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    TARGET_USER_ID VARCHAR(80) REFERENCES USERS(USER_ID) ON DELETE SET NULL,
    TODO_TTL VARCHAR(200) NOT NULL,
    TODO_CN TEXT,
    DONE_YN CHAR(1) NOT NULL DEFAULT 'N',
    DUE_DT TIMESTAMP,
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_CHG_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS USER_CATEGORY_RECOMMEND (
    RECOMMEND_ID BIGSERIAL PRIMARY KEY,
    FROM_USER_ID VARCHAR(80) NOT NULL REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    TO_USER_ID VARCHAR(80) NOT NULL REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    BBS_CTGR_CD VARCHAR(20) NOT NULL,
    MESSAGE VARCHAR(255),
    ACCEPTED_YN CHAR(1),
    READ_YN CHAR(1) NOT NULL DEFAULT 'N',
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ACCEPTED_DT TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IDX_USER_FEED_READ_USER ON USER_FEED_READ (USER_ID, READ_DT DESC);
CREATE INDEX IF NOT EXISTS IDX_USER_SAVED_POST_USER ON USER_SAVED_POST (USER_ID, CRT_DT DESC);
CREATE INDEX IF NOT EXISTS IDX_USER_FAVORITE_USER_USER ON USER_FAVORITE_USER (USER_ID, CRT_DT DESC);
CREATE INDEX IF NOT EXISTS IDX_USER_TODO_USER ON USER_TODO (USER_ID, DONE_YN, DUE_DT);
CREATE INDEX IF NOT EXISTS IDX_USER_CATEGORY_RECOMMEND_TO_USER ON USER_CATEGORY_RECOMMEND (TO_USER_ID, READ_YN, CRT_DT DESC);
CREATE INDEX IF NOT EXISTS IDX_USER_CATEGORY_RECOMMEND_FROM_USER ON USER_CATEGORY_RECOMMEND (FROM_USER_ID, CRT_DT DESC);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'user_feed_read')
       AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_user_feed_read_pst_id') THEN
        ALTER TABLE user_feed_read
            ADD CONSTRAINT fk_user_feed_read_pst_id
            FOREIGN KEY (pst_id) REFERENCES board(pst_id) ON DELETE CASCADE;
    END IF;

    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'user_saved_post')
       AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_user_saved_post_pst_id') THEN
        ALTER TABLE user_saved_post
            ADD CONSTRAINT fk_user_saved_post_pst_id
            FOREIGN KEY (pst_id) REFERENCES board(pst_id) ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'meeting_recurring_booking'
          AND column_name = 'recurring_id'
          AND data_type <> 'integer'
    ) THEN
        ALTER TABLE meeting_recurring_booking
            ALTER COLUMN recurring_id TYPE integer
            USING NULLIF(recurring_id, '')::integer;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'meeting_recurring_booking'
          AND column_name = 'interval'
          AND data_type <> 'integer'
    ) THEN
        ALTER TABLE meeting_recurring_booking
            ALTER COLUMN interval TYPE integer
            USING NULLIF(interval, '')::integer;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'meeting_recurring_booking'
          AND column_name = 'start_date'
          AND data_type <> 'date'
    ) THEN
        ALTER TABLE meeting_recurring_booking
            ALTER COLUMN start_date TYPE date
            USING start_date::date;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'meeting_recurring_booking'
          AND column_name = 'end_date'
          AND data_type <> 'date'
    ) THEN
        ALTER TABLE meeting_recurring_booking
            ALTER COLUMN end_date TYPE date
            USING end_date::date;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'meeting_recurring_booking'
          AND column_name = 'start_time'
          AND data_type <> 'integer'
    ) THEN
        ALTER TABLE meeting_recurring_booking
            ALTER COLUMN start_time TYPE integer
            USING EXTRACT(HOUR FROM start_time)::integer;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'meeting_recurring_booking'
          AND column_name = 'end_time'
          AND data_type <> 'integer'
    ) THEN
        ALTER TABLE meeting_recurring_booking
            ALTER COLUMN end_time TYPE integer
            USING EXTRACT(HOUR FROM end_time)::integer;
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'meeting_reservation'
          AND column_name = 'reservation_id'
          AND data_type <> 'integer'
    ) THEN
        ALTER TABLE meeting_reservation
            ALTER COLUMN reservation_id TYPE integer
            USING NULLIF(reservation_id, '')::integer;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'meeting_reservation'
          AND column_name = 'recurring_id'
          AND data_type <> 'integer'
    ) THEN
        ALTER TABLE meeting_reservation
            ALTER COLUMN recurring_id TYPE integer
            USING NULLIF(recurring_id, '')::integer;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'meeting_reservation'
          AND column_name = 'meeting_date'
          AND data_type <> 'date'
    ) THEN
        ALTER TABLE meeting_reservation
            ALTER COLUMN meeting_date TYPE date
            USING meeting_date::date;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'meeting_reservation'
          AND column_name = 'start_time'
          AND data_type <> 'integer'
    ) THEN
        ALTER TABLE meeting_reservation
            ALTER COLUMN start_time TYPE integer
            USING EXTRACT(HOUR FROM start_time)::integer;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'meeting_reservation'
          AND column_name = 'end_time'
          AND data_type <> 'integer'
    ) THEN
        ALTER TABLE meeting_reservation
            ALTER COLUMN end_time TYPE integer
            USING EXTRACT(HOUR FROM end_time)::integer;
    END IF;
END $$;
