-- Auto-generated from MyBatis mapper SQL
-- Generated at 2026-03-06 03:11:30

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SEQUENCE IF NOT EXISTS ALRM_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS ATRZ_DOC_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS ATRZ_DOC_TMPL_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS ATRZ_LINE_SQN_SEQ;
CREATE SEQUENCE IF NOT EXISTS AUTHORIZATION_TEMP_SEQ;
CREATE SEQUENCE IF NOT EXISTS BIZ_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS CHKLIST_SQN_SEQ;
CREATE SEQUENCE IF NOT EXISTS CMNT_SQN_SEQ;
CREATE SEQUENCE IF NOT EXISTS CONTRACT_AUDIT_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS CONTRACT_BATCH_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS CONTRACT_FIELD_VALUE_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS CONTRACT_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS CONTRACT_INVITATION_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS CONTRACT_REQ_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS CONTRACT_SETTING_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS CONTRACT_SIGNER_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS CONTRACT_TMPL_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS CONTRACT_TMPL_VER_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS CSTM_LINE_BM_SQN_SEQ;
CREATE SEQUENCE IF NOT EXISTS DEPT_SCHD_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS EMAIL_CONT_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS FILE_DETAIL_SEQ;
CREATE SEQUENCE IF NOT EXISTS FILE_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS FOLDER_SQN_SEQ;
CREATE SEQUENCE IF NOT EXISTS MAIL_RCVR_SEQ;
CREATE SEQUENCE IF NOT EXISTS MAIL_SDPT_SQN_SEQ;
CREATE SEQUENCE IF NOT EXISTS MEETING_RECURRING_BOOKING_SEQ;
CREATE SEQUENCE IF NOT EXISTS MENU_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS MSGR_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS NWMN_SQN_SEQ;
CREATE SEQUENCE IF NOT EXISTS PST_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS SEQ_MEETING_MEMO;
CREATE SEQUENCE IF NOT EXISTS SEQ_MEETING_RESERVATION;
CREATE SEQUENCE IF NOT EXISTS USER_HISTORY_SEQ;
CREATE SEQUENCE IF NOT EXISTS USER_SCHEDULE_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS VACT_SQN_SEQ;

CREATE TABLE IF NOT EXISTS ALARM_LOG (
    ALARM_CATEGORY VARCHAR(255),
    ALARM_CODE VARCHAR(255),
    ALARM_ID VARCHAR(80),
    ALARM_MESSAGE VARCHAR(255),
    CREATED_DT TIMESTAMP,
    READ_DT TIMESTAMP,
    READ_YN CHAR(1) DEFAULT 'N',
    RECEIVER_ID VARCHAR(80),
    RELATED_URL VARCHAR(500),
    SENDER_ID VARCHAR(80)
);

CREATE TABLE IF NOT EXISTS ALARM_TEMPLATE (
    ALARM_CATEGORY VARCHAR(255),
    ALARM_CODE VARCHAR(255),
    ALARM_MESSAGE VARCHAR(255),
    ALARM_TITLE VARCHAR(255),
    RELATED_URL VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS ATTENDANCE_DEPART_STATUS (
    BZTR_YN CHAR(1) DEFAULT 'N',
    EARLY_YN CHAR(1) DEFAULT 'N',
    LATE_YN CHAR(1) DEFAULT 'N',
    OVERTIME_HR VARCHAR(255),
    OVERTIME_YN CHAR(1) DEFAULT 'N',
    USER_ID VARCHAR(80),
    VACT_YN CHAR(1) DEFAULT 'N',
    WORK_BGNG_DT TIMESTAMP,
    WORK_END_DT TIMESTAMP,
    WORK_HR VARCHAR(255),
    WORK_STTS_CD VARCHAR(40),
    WORK_YMD TIMESTAMP
);

CREATE TABLE IF NOT EXISTS AUTHORIZATION_DOCUMENT (
    ATRZ_DOC_ID VARCHAR(80),
    ATRZ_DOC_TMPL_ID VARCHAR(80),
    ATRZ_DOC_TTL VARCHAR(255),
    ATRZ_FILE_ID VARCHAR(80),
    ATRZ_SBMT_DT TIMESTAMP,
    ATRZ_USER_ID VARCHAR(80),
    CRNT_ATRZ_STEP_CD VARCHAR(40),
    DATE VARCHAR(255),
    DEL_YN CHAR(1) DEFAULT 'N',
    HTML_DATA TEXT,
    OPEN_YN CHAR(1) DEFAULT 'N'
);

CREATE TABLE IF NOT EXISTS AUTHORIZATION_DOCUMENT_PDF (
    ATRZ_DOC_ID VARCHAR(80) NOT NULL,
    CRT_DT TIMESTAMP,
    EXT_FILE VARCHAR(255),
    FILE_MIME_TYPE VARCHAR(255),
    FILE_PATH TEXT,
    FILE_SIZE VARCHAR(255),
    SAVE_FILE_NM VARCHAR(200),
    CONSTRAINT PK_AUTHORIZATION_DOCUMENT_PDF PRIMARY KEY (ATRZ_DOC_ID)
);

CREATE TABLE IF NOT EXISTS AUTHORIZATION_DOCUMENT_RECEIVER (
    ATRZ_DOC_ID VARCHAR(80) NOT NULL,
    ATRZ_RCVR_ID VARCHAR(80) NOT NULL,
    OPEN_DT TIMESTAMP,
    OPEN_YN CHAR(1) DEFAULT 'N',
    CONSTRAINT PK_AUTHORIZATION_DOCUMENT_RECEIVER PRIMARY KEY (ATRZ_DOC_ID, ATRZ_RCVR_ID)
);

CREATE TABLE IF NOT EXISTS AUTHORIZATION_DOCUMENT_TEMPLATE (
    APPR_ATRZ_DOC_YN CHAR(1) DEFAULT 'N',
    ATRZ_CATEGORY VARCHAR(255),
    ATRZ_DESCRIPTION VARCHAR(255),
    ATRZ_DOC_CD VARCHAR(40),
    ATRZ_DOC_TMPL_ID VARCHAR(80),
    ATRZ_DOC_TMPL_NM VARCHAR(200),
    ATRZ_SAVE_YEAR VARCHAR(255),
    ATRZ_SECURE_LVL VARCHAR(255),
    CRT_DT TIMESTAMP,
    DEL_YN CHAR(1) DEFAULT 'N',
    HTML_CONTENTS TEXT
);

CREATE TABLE IF NOT EXISTS AUTHORIZATION_LINE (
    APPR_ATRZ_YN CHAR(1) DEFAULT 'N',
    ATRZ_ACT VARCHAR(255),
    ATRZ_APPR_STTS VARCHAR(255),
    ATRZ_APPR_USER_ID VARCHAR(80),
    ATRZ_DOC_ID VARCHAR(80),
    ATRZ_LINE_SEQ INTEGER,
    ATRZ_LINE_SQN INTEGER,
    ATRZ_OPNN VARCHAR(255),
    PRCS_DT TIMESTAMP,
    SIGN_FILE_ID VARCHAR(80)
);

CREATE TABLE IF NOT EXISTS AUTHORIZATION_TEMP (
    ATRZ_DOC_TMPL_ID VARCHAR(80),
    ATRZ_DOC_TTL VARCHAR(255),
    ATRZ_FILE_ID VARCHAR(80),
    ATRZ_SBMT_DT TIMESTAMP,
    ATRZ_TEMP_SQN VARCHAR(255),
    ATRZ_USER_ID VARCHAR(80),
    DEL_YN CHAR(1) DEFAULT 'N',
    HTML_DATA TEXT,
    OPEN_YN CHAR(1) DEFAULT 'N'
);

CREATE TABLE IF NOT EXISTS BOARD (
    BBS_CTGR_CD VARCHAR(40),
    COMMUNITY_ID BIGINT,
    CONTENTS TEXT,
    CRT_USER_ID VARCHAR(80),
    DEL_YN CHAR(1) DEFAULT 'N',
    FIXED_YN CHAR(1) DEFAULT 'N',
    FRST_CRT_DT TIMESTAMP,
    IMPORTANCE_CD VARCHAR(20) DEFAULT 'normal',
    LAST_CHG_DT TIMESTAMP,
    LAST_CHG_USER_ID VARCHAR(80),
    LINK_URL VARCHAR(500),
    PST_FILE_ID VARCHAR(80),
    PST_ID VARCHAR(80),
    PST_TTL VARCHAR(255),
    PST_TYPE_CD VARCHAR(20) DEFAULT 'story',
    PUBLISHED_DT TIMESTAMP,
    PUBLISH_STATE_CD VARCHAR(20) DEFAULT 'published',
    RESERVED_PUBLISH_DT TIMESTAMP,
    VIEW_CNT INTEGER,
    VISIBILITY_CD VARCHAR(20) DEFAULT 'community'
);

CREATE TABLE IF NOT EXISTS BOARD_COMMENT (
    CMNT_SQN VARCHAR(255),
    CMNT_FILE_ID VARCHAR(80),
    CONTENTS TEXT,
    CRT_USER_ID VARCHAR(80),
    DEL_YN CHAR(1) DEFAULT 'N',
    FRST_CRT_DT TIMESTAMP,
    LAST_CHG_DT TIMESTAMP,
    LAST_CHG_USER_ID VARCHAR(80),
    PST_ID VARCHAR(80),
    UP_CMNT_SQN VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS BOARD_POLL (
    PST_ID VARCHAR(80) NOT NULL,
    ANONYMOUS_YN CHAR(1) DEFAULT 'N',
    DEADLINE_DT TIMESTAMP,
    MULTIPLE_YN CHAR(1) DEFAULT 'N',
    PARTICIPANT_OPEN_YN CHAR(1) DEFAULT 'Y',
    RESULT_OPEN_YN CHAR(1) DEFAULT 'Y',
    CONSTRAINT PK_BOARD_POLL PRIMARY KEY (PST_ID)
);

CREATE TABLE IF NOT EXISTS BOARD_POLL_OPTION (
    OPTION_ID BIGSERIAL,
    OPTION_TEXT VARCHAR(255) NOT NULL,
    PST_ID VARCHAR(80) NOT NULL,
    SORT_ORDR INTEGER DEFAULT 1,
    CONSTRAINT PK_BOARD_POLL_OPTION PRIMARY KEY (OPTION_ID)
);

CREATE TABLE IF NOT EXISTS BOARD_POLL_RESPONSE (
    RESPONSE_ID BIGSERIAL,
    CRT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    OPTION_ID BIGINT NOT NULL,
    PST_ID VARCHAR(80) NOT NULL,
    USER_ID VARCHAR(80) NOT NULL,
    CONSTRAINT PK_BOARD_POLL_RESPONSE PRIMARY KEY (RESPONSE_ID)
);

CREATE TABLE IF NOT EXISTS BOARD_SCHEDULE (
    PST_ID VARCHAR(80) NOT NULL,
    ALLDAY_YN CHAR(1) DEFAULT 'N',
    END_DT TIMESTAMP NOT NULL,
    MEETING_RESERVATION_ID INTEGER,
    MEETING_ROOM_ID VARCHAR(80),
    PLACE_TEXT VARCHAR(255),
    PLACE_URL VARCHAR(500),
    REMINDER_MINUTES INTEGER,
    REPEAT_RULE VARCHAR(255),
    START_DT TIMESTAMP NOT NULL,
    VIDEO_MEETING_YN CHAR(1) DEFAULT 'N',
    CONSTRAINT PK_BOARD_SCHEDULE PRIMARY KEY (PST_ID)
);

CREATE TABLE IF NOT EXISTS BOARD_SCHEDULE_ATTENDEE (
    ATTENDANCE_STTS_CD VARCHAR(20) DEFAULT 'invited',
    PST_ID VARCHAR(80) NOT NULL,
    USER_ID VARCHAR(80) NOT NULL,
    CONSTRAINT PK_BOARD_SCHEDULE_ATTENDEE PRIMARY KEY (PST_ID, USER_ID)
);

CREATE TABLE IF NOT EXISTS BOARD_TODO (
    PST_ID VARCHAR(80) NOT NULL,
    DUE_DT TIMESTAMP,
    STATUS_CD VARCHAR(20) DEFAULT 'requested',
    CONSTRAINT PK_BOARD_TODO PRIMARY KEY (PST_ID)
);

CREATE TABLE IF NOT EXISTS BOARD_TODO_ASSIGNEE (
    CRT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_CHG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PST_ID VARCHAR(80) NOT NULL,
    STATUS_CD VARCHAR(20) DEFAULT 'requested',
    USER_ID VARCHAR(80) NOT NULL,
    CONSTRAINT PK_BOARD_TODO_ASSIGNEE PRIMARY KEY (PST_ID, USER_ID)
);

CREATE TABLE IF NOT EXISTS BOARD_POST_REACTION (
    CRT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PST_ID VARCHAR(80) NOT NULL,
    REACTION_CD VARCHAR(20) DEFAULT 'like',
    USER_ID VARCHAR(80) NOT NULL,
    CONSTRAINT PK_BOARD_POST_REACTION PRIMARY KEY (PST_ID, USER_ID, REACTION_CD)
);

CREATE TABLE IF NOT EXISTS BOARD_POST_MENTION (
    CRT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PST_ID VARCHAR(80) NOT NULL,
    USER_ID VARCHAR(80) NOT NULL,
    CONSTRAINT PK_BOARD_POST_MENTION PRIMARY KEY (PST_ID, USER_ID)
);

CREATE TABLE IF NOT EXISTS BOARD_COMMENT_MENTION (
    CMNT_SQN VARCHAR(255) NOT NULL,
    CRT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USER_ID VARCHAR(80) NOT NULL,
    CONSTRAINT PK_BOARD_COMMENT_MENTION PRIMARY KEY (CMNT_SQN, USER_ID)
);

CREATE TABLE IF NOT EXISTS BOARD_REPORT (
    REPORT_ID BIGSERIAL,
    CRT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PST_ID VARCHAR(80) NOT NULL,
    REASON_TEXT VARCHAR(500) NOT NULL,
    REPORTER_ID VARCHAR(80) NOT NULL,
    STATUS_CD VARCHAR(20) DEFAULT 'submitted',
    CONSTRAINT PK_BOARD_REPORT PRIMARY KEY (REPORT_ID)
);

CREATE TABLE IF NOT EXISTS BOARD_SHARE (
    SHARE_ID BIGSERIAL,
    CRT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PST_ID VARCHAR(80) NOT NULL,
    SHARE_TARGET_ID VARCHAR(80) NOT NULL,
    SHARE_TYPE_CD VARCHAR(20) NOT NULL,
    SHARE_USER_ID VARCHAR(80) NOT NULL,
    CONSTRAINT PK_BOARD_SHARE PRIMARY KEY (SHARE_ID)
);

CREATE TABLE IF NOT EXISTS BOARD_SHARE_RECIPIENT (
    CRT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PST_ID VARCHAR(80) NOT NULL,
    RECIPIENT_USER_ID VARCHAR(80) NOT NULL,
    SHARE_ID BIGINT NOT NULL,
    CONSTRAINT PK_BOARD_SHARE_RECIPIENT PRIMARY KEY (SHARE_ID, RECIPIENT_USER_ID)
);

CREATE TABLE IF NOT EXISTS CONTRACT_COMPANY_SETTING (
    ADMIN_READY_YN CHAR(1) DEFAULT 'N',
    CHECKLIST_JSON TEXT,
    COMPANY_NM VARCHAR(200),
    CRT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CRT_USER_ID VARCHAR(80),
    GUIDE_ACK_YN CHAR(1) DEFAULT 'N',
    LAST_CHG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_CHG_USER_ID VARCHAR(80),
    NOTE_TEXT TEXT,
    PROVIDER_NM VARCHAR(80),
    SEAL_FILE_ID VARCHAR(80),
    SENDER_EMAIL VARCHAR(255),
    SENDER_NM VARCHAR(120),
    SENDER_TELNO VARCHAR(30),
    SETTING_ID BIGINT NOT NULL DEFAULT nextval('CONTRACT_SETTING_ID_SEQ'),
    CONSTRAINT PK_CONTRACT_COMPANY_SETTING PRIMARY KEY (SETTING_ID)
);

CREATE TABLE IF NOT EXISTS CONTRACT_TEMPLATE_REQUEST (
    CONVERTED_TEMPLATE_ID BIGINT,
    CRT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_CHG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MARKED_FILE_ID VARCHAR(80),
    REQUESTER_USER_ID VARCHAR(80),
    REQUEST_ID BIGINT NOT NULL DEFAULT nextval('CONTRACT_REQ_ID_SEQ'),
    REQUEST_NOTE TEXT,
    REQUEST_REF VARCHAR(80),
    REQUEST_STATUS_CD VARCHAR(20) DEFAULT 'requested',
    REQUEST_TITLE VARCHAR(200) NOT NULL,
    REVIEW_DT TIMESTAMP,
    REVIEW_NOTE TEXT,
    REVIEW_USER_ID VARCHAR(80),
    SEAL_FILE_ID VARCHAR(80),
    SOURCE_FILE_ID VARCHAR(80),
    CONSTRAINT PK_CONTRACT_TEMPLATE_REQUEST PRIMARY KEY (REQUEST_ID)
);

CREATE TABLE IF NOT EXISTS CONTRACT_TEMPLATE (
    ACTIVE_YN CHAR(1) DEFAULT 'Y',
    CRT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CRT_USER_ID VARCHAR(80),
    LAST_CHG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PUBLISHED_VERSION_ID BIGINT,
    REQUEST_ID BIGINT,
    TEMPLATE_CATEGORY_CD VARCHAR(40) DEFAULT 'general',
    TEMPLATE_CODE VARCHAR(80),
    TEMPLATE_DESC TEXT,
    TEMPLATE_ID BIGINT NOT NULL DEFAULT nextval('CONTRACT_TMPL_ID_SEQ'),
    TEMPLATE_NM VARCHAR(200) NOT NULL,
    CONSTRAINT PK_CONTRACT_TEMPLATE PRIMARY KEY (TEMPLATE_ID)
);

CREATE TABLE IF NOT EXISTS CONTRACT_TEMPLATE_VERSION (
    BACKGROUND_FILE_ID VARCHAR(80),
    CRT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CRT_USER_ID VARCHAR(80),
    LAST_CHG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAYOUT_JSON TEXT,
    PUBLISHED_DT TIMESTAMP,
    SCHEMA_JSON TEXT,
    SOURCE_FILE_ID VARCHAR(80),
    TEMPLATE_ID BIGINT NOT NULL,
    TEMPLATE_VERSION_ID BIGINT NOT NULL DEFAULT nextval('CONTRACT_TMPL_VER_ID_SEQ'),
    VERSION_LABEL VARCHAR(120),
    VERSION_NO INTEGER NOT NULL,
    VERSION_NOTE TEXT,
    VERSION_STATUS_CD VARCHAR(20) DEFAULT 'draft',
    CONSTRAINT PK_CONTRACT_TEMPLATE_VERSION PRIMARY KEY (TEMPLATE_VERSION_ID)
);

CREATE TABLE IF NOT EXISTS CONTRACT_BATCH (
    BATCH_ID BIGINT NOT NULL DEFAULT nextval('CONTRACT_BATCH_ID_SEQ'),
    BATCH_REF VARCHAR(80),
    BATCH_TITLE VARCHAR(200) NOT NULL,
    CREATOR_USER_ID VARCHAR(80),
    CRT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FAILED_COUNT INTEGER DEFAULT 0,
    LAST_CHG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    RESULT_JSON TEXT,
    SOURCE_FILE_ID VARCHAR(80),
    SUCCESS_COUNT INTEGER DEFAULT 0,
    TEMPLATE_ID BIGINT,
    TEMPLATE_VERSION_ID BIGINT,
    TOTAL_COUNT INTEGER DEFAULT 0,
    CONSTRAINT PK_CONTRACT_BATCH PRIMARY KEY (BATCH_ID)
);

CREATE TABLE IF NOT EXISTS CONTRACT_DOCUMENT (
    BATCH_ID BIGINT,
    CANCELLED_DT TIMESTAMP,
    CANCELLED_REASON VARCHAR(500),
    COMPANY_SNAPSHOT_JSON TEXT,
    COMPLETED_DT TIMESTAMP,
    CONTRACT_ID BIGINT NOT NULL DEFAULT nextval('CONTRACT_ID_SEQ'),
    CONTRACT_MESSAGE TEXT,
    CONTRACT_REF VARCHAR(80),
    CONTRACT_TITLE VARCHAR(255) NOT NULL,
    CREATOR_USER_ID VARCHAR(80),
    CRT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CURRENT_SIGN_ORDER INTEGER DEFAULT 1,
    EXPIRES_DT TIMESTAMP,
    FINAL_FILE_ID VARCHAR(80),
    FINAL_HTML_DATA TEXT,
    LAST_CHG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SEND_TYPE_CD VARCHAR(20) DEFAULT 'remote',
    SENDER_EMAIL VARCHAR(255),
    SENDER_NM VARCHAR(120),
    SENDER_TELNO VARCHAR(30),
    SENT_DT TIMESTAMP,
    SIGNING_FLOW_CD VARCHAR(20) DEFAULT 'parallel',
    STATUS_CD VARCHAR(20) DEFAULT 'draft',
    TEMPLATE_ID BIGINT,
    TEMPLATE_LAYOUT_JSON TEXT,
    TEMPLATE_SCHEMA_JSON TEXT,
    TEMPLATE_VERSION_ID BIGINT,
    TOTAL_SIGNER_COUNT INTEGER DEFAULT 0,
    CONSTRAINT PK_CONTRACT_DOCUMENT PRIMARY KEY (CONTRACT_ID)
);

CREATE TABLE IF NOT EXISTS CONTRACT_SIGNER (
    CLAIMED_EMAIL VARCHAR(255),
    CLAIMED_NM VARCHAR(120),
    CLAIMED_TELNO VARCHAR(30),
    CONTRACT_ID BIGINT NOT NULL,
    DECLINED_REASON VARCHAR(500),
    INITIAL_DATA TEXT,
    INTERNAL_USER_ID VARCHAR(80),
    LAST_CHG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    OPENED_DT TIMESTAMP,
    SIGNATURE_DATA TEXT,
    SIGNED_DT TIMESTAMP,
    SIGNER_EMAIL VARCHAR(255),
    SIGNER_ID BIGINT NOT NULL DEFAULT nextval('CONTRACT_SIGNER_ID_SEQ'),
    SIGNER_NM VARCHAR(120) NOT NULL,
    SIGNER_ORDER INTEGER DEFAULT 1,
    SIGNER_ROLE_CD VARCHAR(20) DEFAULT 'signer',
    SIGNER_TELNO VARCHAR(30),
    SIGNER_TYPE_CD VARCHAR(20) DEFAULT 'external',
    STATUS_CD VARCHAR(20) DEFAULT 'pending',
    CONSTRAINT PK_CONTRACT_SIGNER PRIMARY KEY (SIGNER_ID)
);

CREATE TABLE IF NOT EXISTS CONTRACT_INVITATION (
    ACTIVE_YN CHAR(1) DEFAULT 'Y',
    CHANNEL_CD VARCHAR(20) DEFAULT 'remote',
    COMPLETED_DT TIMESTAMP,
    CONTRACT_ID BIGINT NOT NULL,
    CRT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELIVERY_NOTE VARCHAR(255),
    DELIVERY_STATUS_CD VARCHAR(20) DEFAULT 'pending',
    EXPIRES_DT TIMESTAMP,
    INVITATION_ID BIGINT NOT NULL DEFAULT nextval('CONTRACT_INVITATION_ID_SEQ'),
    LAST_CHG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    OPENED_DT TIMESTAMP,
    SENT_DT TIMESTAMP,
    SIGNER_ID BIGINT NOT NULL,
    TOKEN_HASH VARCHAR(255),
    TOKEN_HINT VARCHAR(24),
    CONSTRAINT PK_CONTRACT_INVITATION PRIMARY KEY (INVITATION_ID)
);

CREATE TABLE IF NOT EXISTS CONTRACT_FIELD_VALUE (
    CONTRACT_ID BIGINT NOT NULL,
    FIELD_KEY VARCHAR(120) NOT NULL,
    FIELD_VALUE TEXT,
    FIELD_VALUE_ID BIGINT NOT NULL DEFAULT nextval('CONTRACT_FIELD_VALUE_ID_SEQ'),
    LAST_CHG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REPEAT_GROUP_KEY VARCHAR(120),
    ROW_INDEX INTEGER DEFAULT 0,
    SIGNER_ID BIGINT,
    CONSTRAINT PK_CONTRACT_FIELD_VALUE PRIMARY KEY (FIELD_VALUE_ID)
);

CREATE TABLE IF NOT EXISTS CONTRACT_AUDIT_LOG (
    ACTION_CD VARCHAR(40) NOT NULL,
    ACTION_MESSAGE VARCHAR(500),
    ACTOR_NM VARCHAR(120),
    ACTOR_TYPE_CD VARCHAR(20) DEFAULT 'system',
    ACTOR_USER_ID VARCHAR(80),
    AUDIT_ID BIGINT NOT NULL DEFAULT nextval('CONTRACT_AUDIT_ID_SEQ'),
    CONTRACT_ID BIGINT NOT NULL,
    CRT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PAYLOAD_JSON TEXT,
    SIGNER_ID BIGINT,
    CONSTRAINT PK_CONTRACT_AUDIT_LOG PRIMARY KEY (AUDIT_ID)
);

CREATE TABLE IF NOT EXISTS BUSINESS_TRIP (
    ALLDAY VARCHAR(255),
    ATRZ_DOC_ID VARCHAR(80),
    BZTR_BGNG_DT TIMESTAMP,
    BZTR_CD VARCHAR(40),
    BZTR_END_DT TIMESTAMP,
    BZTR_EXPLN VARCHAR(255),
    BZTR_SQN VARCHAR(255),
    BZTR_USER_ID VARCHAR(80)
);

CREATE TABLE IF NOT EXISTS COMMON_CODE (
    CODE_GRP_ID VARCHAR(80),
    CODE_ID VARCHAR(80) NOT NULL,
    CODE_NM VARCHAR(200),
    USE_YN CHAR(1) DEFAULT 'N',
    CONSTRAINT PK_COMMON_CODE PRIMARY KEY (CODE_ID)
);

CREATE TABLE IF NOT EXISTS COMMON_CODE_GROUP (
    CODE_GRP_ID VARCHAR(80) NOT NULL,
    CODE_GRP_NM VARCHAR(200),
    USE_YN CHAR(1) DEFAULT 'N',
    CONSTRAINT PK_COMMON_CODE_GROUP PRIMARY KEY (CODE_GRP_ID)
);

CREATE TABLE IF NOT EXISTS CUSTOM_LINE_BOOKMARK (
    APPR_ATRZ_YN CHAR(1) DEFAULT 'N',
    ATRZ_APPR_ID VARCHAR(80),
    ATRZ_LINE_SEQ INTEGER,
    CSTM_LINE_BM_NM VARCHAR(200),
    CSTM_LINE_BM_SQN VARCHAR(255),
    USER_ID VARCHAR(80)
);

CREATE TABLE IF NOT EXISTS DEPARTMENT (
    DEPT_ID VARCHAR(80) NOT NULL,
    DEPT_NM VARCHAR(200),
    SORT_NUM INTEGER,
    UP_DEPT_ID VARCHAR(80),
    USE_YN CHAR(1) DEFAULT 'N',
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY (DEPT_ID)
);

CREATE TABLE IF NOT EXISTS DEPARTMENT_FILE_MAPPING (
    DEPT_FILE_ID VARCHAR(80) NOT NULL,
    DEPT_ID VARCHAR(80) NOT NULL,
    CONSTRAINT PK_DEPARTMENT_FILE_MAPPING PRIMARY KEY (DEPT_FILE_ID, DEPT_ID)
);

CREATE TABLE IF NOT EXISTS DEPARTMENT_SCHEDULE (
    ALLDAY VARCHAR(255),
    DEL_YN CHAR(1) DEFAULT 'N',
    DEPT_ID VARCHAR(80),
    DEPT_SCHD_CRT_USER_ID VARCHAR(80),
    DEPT_SCHD_EXPLN VARCHAR(255),
    DEPT_SCHD_ID VARCHAR(80),
    SCHD_END_DT TIMESTAMP,
    SCHD_STRT_DT TIMESTAMP,
    SCHD_TTL VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS EMAIL_BOX (
    DEL_DT TIMESTAMP,
    DEL_YN CHAR(1) DEFAULT 'N',
    EMAIL_CONT_ID VARCHAR(80),
    MAILBOX_ID VARCHAR(80),
    MAILBOX_NM VARCHAR(200),
    MAILBOX_TYPE_CD VARCHAR(40),
    READ_DT TIMESTAMP,
    READ_YN CHAR(1) DEFAULT 'N',
    SORT_NUM INTEGER,
    UP_MAILBOX_ID VARCHAR(80),
    USER_ID VARCHAR(80)
);

CREATE TABLE IF NOT EXISTS EMAIL_CONTENT (
    CONTENT TEXT,
    DATE VARCHAR(255),
    EMAIL_CONT_ID VARCHAR(80),
    IMPT_MAIL_YN CHAR(1) DEFAULT 'N',
    MAIL_FILE_ID VARCHAR(80),
    SEND_DATE TIMESTAMP,
    SUBJECT VARCHAR(255),
    USER_ID VARCHAR(80)
);

CREATE TABLE IF NOT EXISTS EMAIL_MAPPING (
    DEL_DT TIMESTAMP,
    DEL_YN CHAR(1) DEFAULT 'N',
    EMAIL_CONT_ID VARCHAR(80) NOT NULL,
    MAILBOX_ID VARCHAR(80) NOT NULL,
    READ_DT TIMESTAMP,
    READ_YN CHAR(1) DEFAULT 'N',
    CONSTRAINT PK_EMAIL_MAPPING PRIMARY KEY (EMAIL_CONT_ID, MAILBOX_ID)
);

CREATE TABLE IF NOT EXISTS EMAIL_RECEIVER (
    EMAIL_CONT_ID VARCHAR(80) NOT NULL,
    MAIL_RCVR_SQN VARCHAR(255),
    USER_ID VARCHAR(80) NOT NULL,
    CONSTRAINT PK_EMAIL_RECEIVER PRIMARY KEY (EMAIL_CONT_ID, USER_ID)
);

CREATE TABLE IF NOT EXISTS EMAIL_SENDER_PARTY (
    EMAIL_CONT_ID VARCHAR(80) NOT NULL,
    MAIL_SDPT_SQN VARCHAR(255),
    USER_ID VARCHAR(80) NOT NULL,
    CONSTRAINT PK_EMAIL_SENDER_PARTY PRIMARY KEY (EMAIL_CONT_ID, USER_ID)
);

CREATE TABLE IF NOT EXISTS FEATURES (
    FEATURE_ID VARCHAR(80) NOT NULL,
    FEATURE_NAME VARCHAR(200),
    CONSTRAINT PK_FEATURES PRIMARY KEY (FEATURE_ID)
);

CREATE TABLE IF NOT EXISTS FILE_DETAIL (
    DEL_YN CHAR(1) DEFAULT 'N',
    EXT_FILE VARCHAR(255),
    FILE_ID VARCHAR(80) NOT NULL,
    FILE_MIME_TYPE VARCHAR(255),
    FILE_PATH TEXT,
    FILE_SEQ INTEGER,
    FILE_SIZE VARCHAR(255),
    ORGN_FILE_NM VARCHAR(200),
    SAVE_FILE_NM VARCHAR(200),
    CONSTRAINT PK_FILE_DETAIL PRIMARY KEY (FILE_ID)
);

CREATE TABLE IF NOT EXISTS FILE_MASTER (
    CRT_DT TIMESTAMP,
    CRT_USER_ID VARCHAR(80),
    DEL_YN CHAR(1) DEFAULT 'N',
    FILE_ID VARCHAR(80)
);

CREATE TABLE IF NOT EXISTS FULLCALENDAR_DEPT (
    ALLDAY VARCHAR(255),
    DEPT_ID VARCHAR(80),
    DESCRIPTION VARCHAR(255),
    END_DT TIMESTAMP,
    EVENT_ID VARCHAR(80),
    EVENT_TYPE VARCHAR(255),
    START_DT TIMESTAMP,
    TITLE VARCHAR(255),
    TYPE VARCHAR(255),
    USER_ID VARCHAR(80),
    USER_NM VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS FULLCALENDAR_TEAM (
    ALLDAY VARCHAR(255),
    BIZ_ID VARCHAR(80),
    DESCRIPTION VARCHAR(255),
    END_DT TIMESTAMP,
    EVENT_ID VARCHAR(80),
    EVENT_TYPE VARCHAR(255),
    START_DT TIMESTAMP,
    TITLE VARCHAR(255),
    TYPE VARCHAR(255),
    USER_ID VARCHAR(80),
    USER_NM VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS JOB_GRADE (
    APPR_ATRZ_YN CHAR(1) DEFAULT 'N',
    CRT_DT TIMESTAMP,
    JBGD_CD VARCHAR(40) NOT NULL,
    JBGD_NM VARCHAR(200),
    USE_YN CHAR(1) DEFAULT 'N',
    CONSTRAINT PK_JOB_GRADE PRIMARY KEY (JBGD_CD)
);

CREATE TABLE IF NOT EXISTS MAIN_TASK (
    BIZ_ID VARCHAR(80),
    BIZ_USER_ID VARCHAR(80),
    END_TASK_DT TIMESTAMP,
    STRT_TASK_DT TIMESTAMP,
    TASK_DETAIL VARCHAR(255),
    TASK_FILE_ID VARCHAR(80),
    TASK_ID VARCHAR(80),
    TASK_NM VARCHAR(200),
    TASK_PRGRS VARCHAR(255),
    TASK_STTS_CD VARCHAR(40)
);

CREATE TABLE IF NOT EXISTS MEETING_MEMO (
    CONTENTS TEXT,
    CRT_DT TIMESTAMP,
    MEMO_ID VARCHAR(80),
    TITLE VARCHAR(255),
    USER_ID VARCHAR(80)
);

CREATE TABLE IF NOT EXISTS MEETING_RECURRING_BOOKING (
    CRT_DT TIMESTAMP,
    END_DATE DATE,
    END_TIME INTEGER,
    FREQUENCY VARCHAR(255),
    INTERVAL INTEGER,
    RECURRING_ID INTEGER,
    REJECT_REASON TEXT,
    ROOM_ID VARCHAR(80),
    START_DATE DATE,
    START_TIME INTEGER,
    STATUS VARCHAR(255),
    TITLE VARCHAR(255),
    USER_ID VARCHAR(80)
);

CREATE TABLE IF NOT EXISTS MEETING_RECURRING_WEEKDAY (
    RECURRING_ID VARCHAR(80) NOT NULL,
    WEEKDAY VARCHAR(255),
    CONSTRAINT PK_MEETING_RECURRING_WEEKDAY PRIMARY KEY (RECURRING_ID)
);

CREATE TABLE IF NOT EXISTS MEETING_RESERVATION (
    END_TIME INTEGER,
    JDBCTYPE VARCHAR(255),
    MEETING_DATE DATE,
    RECURRING_ID INTEGER,
    RESERVATION_ID INTEGER,
    ROOM_ID VARCHAR(80),
    START_TIME INTEGER,
    TITLE VARCHAR(255),
    USER_ID VARCHAR(80)
);

CREATE TABLE IF NOT EXISTS MEETING_ROOM (
    CAPACITY INTEGER,
    DEL_DT TIMESTAMP,
    DEL_YN CHAR(1) DEFAULT 'N',
    LOCATION VARCHAR(255),
    ROOM_ID VARCHAR(80) NOT NULL,
    ROOM_NAME VARCHAR(200),
    ROW_NUMBER VARCHAR(255),
    USE_YN CHAR(1) DEFAULT 'N',
    CONSTRAINT PK_MEETING_ROOM PRIMARY KEY (ROOM_ID)
);

CREATE TABLE IF NOT EXISTS MENU (
    CATEGORY_NM VARCHAR(200),
    COST_RATIO_AMT NUMERIC(18,2),
    DEL_YN CHAR(1) DEFAULT 'N',
    INGREDIENT_CONTENT TEXT,
    MARKETING_CONTENT TEXT,
    MENU_FILE_ID VARCHAR(80),
    MENU_ID VARCHAR(80) NOT NULL,
    MENU_NM VARCHAR(200),
    PRICE_AMT NUMERIC(18,2),
    RELEASE_YMD TIMESTAMP,
    STANDARD_CD VARCHAR(40),
    CONSTRAINT PK_MENU PRIMARY KEY (MENU_ID)
);

CREATE TABLE IF NOT EXISTS MESSENGER_CONTENT (
    CONTENTS TEXT,
    DEL_YN CHAR(1) DEFAULT 'N',
    MSG_CONT_ID VARCHAR(80),
    MSG_FILE_ID VARCHAR(80),
    MSGR_ID VARCHAR(80),
    READ_YN CHAR(1) DEFAULT 'N',
    SEND_DT TIMESTAMP,
    USER_ID VARCHAR(80)
);

CREATE TABLE IF NOT EXISTS MESSENGER_READ (
    MSG_CONT_ID VARCHAR(80) NOT NULL,
    READ_DT TIMESTAMP,
    USER_ID VARCHAR(80) NOT NULL,
    CONSTRAINT PK_MESSENGER_READ PRIMARY KEY (MSG_CONT_ID, USER_ID)
);

CREATE TABLE IF NOT EXISTS MESSENGER_ROOM (
    CRT_DT TIMESTAMP,
    DEL_YN CHAR(1) DEFAULT 'N',
    MSGR_ID VARCHAR(80) NOT NULL,
    MSGR_NM VARCHAR(200),
    CONSTRAINT PK_MESSENGER_ROOM PRIMARY KEY (MSGR_ID)
);

CREATE TABLE IF NOT EXISTS MESSENGER_USER (
    JOIN_DT TIMESTAMP,
    LEFT_DT TIMESTAMP,
    MSGR_ID VARCHAR(80),
    USER_ID VARCHAR(80)
);

CREATE TABLE IF NOT EXISTS NEW_MENU_ATRZ (
    ATRZ_DOC_ID VARCHAR(80),
    CATEGORY_NM VARCHAR(200),
    COST_RATIO_AMT NUMERIC(18,2),
    INGREDIENT_CONTENT TEXT,
    MARKETING_CONTENT TEXT,
    MENU_FILE_ID VARCHAR(80),
    MENU_NM VARCHAR(200),
    NWMN_SQN VARCHAR(255),
    PRICE_AMT NUMERIC(18,2),
    RELEASE_YMD TIMESTAMP,
    STANDARD_CD VARCHAR(40)
);

CREATE TABLE IF NOT EXISTS POLICIES (
    CRT_DT TIMESTAMP,
    FEATURE_ID VARCHAR(80) NOT NULL,
    MOD_DT TIMESTAMP,
    REMARK VARCHAR(255),
    CONSTRAINT PK_POLICIES PRIMARY KEY (FEATURE_ID)
);

CREATE TABLE IF NOT EXISTS POLICIES_DETAIL (
    DEPT_ID VARCHAR(80),
    FEATURE_ID VARCHAR(80),
    JBGD_CD VARCHAR(40)
);

CREATE TABLE IF NOT EXISTS PROJECT (
    BIZ_BDGT VARCHAR(255),
    BIZ_DETAIL VARCHAR(255),
    BIZ_FILE_ID VARCHAR(80),
    BIZ_GOAL VARCHAR(255),
    BIZ_ID VARCHAR(80),
    BIZ_NM VARCHAR(200),
    BIZ_PIC_ID VARCHAR(80),
    BIZ_PRGRS VARCHAR(255),
    BIZ_SCOPE VARCHAR(255),
    BIZ_STTS_CD VARCHAR(40),
    BIZ_TYPE_CD VARCHAR(40),
    END_BIZ_DT TIMESTAMP,
    STRT_BIZ_DT TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PROJECT_BOARD (
    BIZ_ID VARCHAR(80),
    BIZ_PST_FILE_ID VARCHAR(80),
    BIZ_PST_ID VARCHAR(80),
    CONTENTS TEXT,
    CRT_USER_ID VARCHAR(80),
    DEL_YN CHAR(1) DEFAULT 'N',
    FRST_CRT_DT TIMESTAMP,
    LAST_CHG_DT TIMESTAMP,
    LAST_CHG_USER_ID VARCHAR(80),
    NOTICE_YN CHAR(1) DEFAULT 'N',
    PST_TTL VARCHAR(255),
    VIEW_CNT INTEGER
);

CREATE TABLE IF NOT EXISTS PROJECT_BOARD_COMMENT (
    BIZ_CMNT_ID VARCHAR(80),
    BIZ_PST_ID VARCHAR(80),
    CONTENTS TEXT,
    CRT_USER_ID VARCHAR(80),
    DEL_YN CHAR(1) DEFAULT 'N',
    FRST_CRT_DT TIMESTAMP,
    LAST_CHG_DT TIMESTAMP,
    LAST_CHG_USER_ID VARCHAR(80),
    UP_BIZ_CMNT_ID VARCHAR(80)
);

CREATE TABLE IF NOT EXISTS PROJECT_MEMBER (
    BIZ_AUTH_CD VARCHAR(40) NOT NULL,
    BIZ_ID VARCHAR(80) NOT NULL,
    BIZ_USER_ID VARCHAR(80) NOT NULL,
    CONSTRAINT PK_PROJECT_MEMBER PRIMARY KEY (BIZ_AUTH_CD, BIZ_ID, BIZ_USER_ID)
);

CREATE TABLE IF NOT EXISTS TASK_CHECKLIST (
    CHKLIST_CONT VARCHAR(255),
    CHKLIST_SQN VARCHAR(255),
    COMPLT_YN CHAR(1) DEFAULT 'N',
    TASK_ID VARCHAR(80) NOT NULL,
    TASK_PIC_ID VARCHAR(80) NOT NULL,
    CONSTRAINT PK_TASK_CHECKLIST PRIMARY KEY (TASK_ID, TASK_PIC_ID)
);

CREATE TABLE IF NOT EXISTS TASK_COMMENT (
    CONTENTS TEXT,
    CRT_DT TIMESTAMP,
    CRT_USER_ID VARCHAR(80),
    TASK_COMM_SQN VARCHAR(255),
    TASK_ID VARCHAR(80)
);

CREATE TABLE IF NOT EXISTS TIME_AND_ATTENDANCE (
    EARLY_YN CHAR(1) DEFAULT 'N',
    LATE_YN CHAR(1) DEFAULT 'N',
    OVERTIME_HR VARCHAR(255),
    OVERTIME_YN CHAR(1) DEFAULT 'N',
    USER_ID VARCHAR(80) NOT NULL,
    WORK_BGNG_DT TIMESTAMP,
    WORK_END_DT TIMESTAMP,
    WORK_HR VARCHAR(255),
    WORK_YMD TIMESTAMP NOT NULL,
    CONSTRAINT PK_TIME_AND_ATTENDANCE PRIMARY KEY (USER_ID, WORK_YMD)
);

CREATE TABLE IF NOT EXISTS USER_FILE_FOLDER (
    CRT_DT TIMESTAMP,
    DEL_YN CHAR(1) DEFAULT 'N',
    FOLDER_NM VARCHAR(200),
    FOLDER_SQN VARCHAR(255),
    FOLDER_TYPE VARCHAR(255),
    UP_FOLDER_SQN VARCHAR(255),
    USER_ID VARCHAR(80) NOT NULL,
    CONSTRAINT PK_USER_FILE_FOLDER PRIMARY KEY (USER_ID)
);

CREATE TABLE IF NOT EXISTS USER_FILE_MAPPING (
    FOLDER_SQN VARCHAR(255),
    USER_FILE_ID VARCHAR(80) NOT NULL,
    USER_FILE_SQN VARCHAR(255),
    USER_ID VARCHAR(80) NOT NULL,
    CONSTRAINT PK_USER_FILE_MAPPING PRIMARY KEY (USER_FILE_ID, USER_ID)
);

CREATE TABLE IF NOT EXISTS USER_HISTORY (
    AFTER_DEPT_ID VARCHAR(80),
    AFTER_JBGD_CD VARCHAR(40),
    BEFORE_DEPT_ID VARCHAR(80),
    BEFORE_JBGD_CD VARCHAR(40),
    CHANGE_TYPE VARCHAR(255),
    CRT_DT TIMESTAMP,
    HISTORY_ID VARCHAR(80),
    REASON TEXT,
    USER_ID VARCHAR(80)
);

CREATE TABLE IF NOT EXISTS USER_MONTHLY_ATTENDANCE (
    ABSENT_DAYS VARCHAR(255),
    DEPT_ID VARCHAR(80),
    DEPT_NM VARCHAR(200),
    EARLY_COUNT INTEGER,
    JBGD_NM VARCHAR(200),
    LATE_COUNT INTEGER,
    OVERTIME_COUNT INTEGER,
    TOTAL_OVERTIME_HR VARCHAR(255),
    TOTAL_WORK_HR VARCHAR(255),
    USER_ID VARCHAR(80),
    USER_NM VARCHAR(200),
    WORK_DAYS VARCHAR(255),
    WORK_MONTH VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS USER_SCHEDULE (
    ALLDAY VARCHAR(255),
    DEL_YN CHAR(1) DEFAULT 'N',
    SCHD_END_DT TIMESTAMP,
    SCHD_STRT_DT TIMESTAMP,
    SCHD_TTL VARCHAR(255),
    USER_ID VARCHAR(80),
    USER_SCHD_EXPLN VARCHAR(255),
    USER_SCHD_ID VARCHAR(80)
);

CREATE TABLE IF NOT EXISTS USER_WEEKLY_ATTENDANCE (
    DEPT_NM VARCHAR(200),
    EARLY_COUNT INTEGER,
    JBGD_NM VARCHAR(200),
    LATE_COUNT INTEGER,
    OVERTIME_COUNT INTEGER,
    TOTAL_OVERTIME_HR VARCHAR(255),
    TOTAL_WORK_HR VARCHAR(255),
    USER_ID VARCHAR(80) NOT NULL,
    USER_NM VARCHAR(200),
    WORK_DAYS VARCHAR(255),
    WORK_WEEK_START_DATE TIMESTAMP,
    CONSTRAINT PK_USER_WEEKLY_ATTENDANCE PRIMARY KEY (USER_ID)
);

CREATE TABLE IF NOT EXISTS USERS (
    DEPT_ID VARCHAR(80),
    EXT_TEL VARCHAR(30),
    HIRE_YMD TIMESTAMP,
    JBGD_CD VARCHAR(40),
    RSGNTN_YMD TIMESTAMP,
    RSGNTN_YN CHAR(1) DEFAULT 'N',
    USER_EMAIL VARCHAR(255),
    USER_ID VARCHAR(80) NOT NULL,
    USER_IMG_FILE_ID VARCHAR(80),
    USER_NM VARCHAR(200),
    USER_PSWD VARCHAR(255),
    USER_ROLE VARCHAR(255),
    USER_OTP_SECRET VARCHAR(255),
    USER_TELNO VARCHAR(30),
    WORK_STTS_CD VARCHAR(40),
    CONSTRAINT PK_USERS PRIMARY KEY (USER_ID)
);

CREATE TABLE IF NOT EXISTS VACATION (
    ALLDAY VARCHAR(255),
    ATRZ_DOC_ID VARCHAR(80),
    USE_VACT_CNT INTEGER,
    VACT_BGNG_DT TIMESTAMP,
    VACT_CD VARCHAR(40),
    VACT_END_DT TIMESTAMP,
    VACT_EXPLN VARCHAR(255),
    VACT_SQN VARCHAR(255),
    VACT_USER_ID VARCHAR(80)
);

