BEGIN;

DELETE FROM BOARD_COMMENT_MENTION WHERE CMNT_SQN IN ('CMNTDEMO001', 'CMNTDEMO002');
DELETE FROM BOARD_COMMENT WHERE CMNT_SQN IN ('CMNTDEMO001', 'CMNTDEMO002');
DELETE FROM BOARD_POST_MENTION WHERE PST_ID IN ('BRDDEMO001', 'BRDDEMO002', 'BRDDEMO003', 'BRDDEMO004', 'BRDDEMO005', 'BRDDEMO006');
DELETE FROM BOARD_POST_REACTION WHERE PST_ID IN ('BRDDEMO001', 'BRDDEMO002', 'BRDDEMO003', 'BRDDEMO004', 'BRDDEMO005', 'BRDDEMO006');
DELETE FROM USER_FEED_READ WHERE PST_ID IN ('BRDDEMO001', 'BRDDEMO002', 'BRDDEMO003', 'BRDDEMO004', 'BRDDEMO005', 'BRDDEMO006');
DELETE FROM USER_SAVED_POST WHERE PST_ID IN ('BRDDEMO001', 'BRDDEMO002', 'BRDDEMO003', 'BRDDEMO004', 'BRDDEMO005', 'BRDDEMO006');
DELETE FROM BOARD_POLL_RESPONSE WHERE PST_ID = 'BRDDEMO002';
DELETE FROM BOARD_POLL_OPTION WHERE PST_ID = 'BRDDEMO002';
DELETE FROM BOARD_POLL WHERE PST_ID = 'BRDDEMO002';
DELETE FROM BOARD_SCHEDULE_ATTENDEE WHERE PST_ID = 'BRDDEMO003';
DELETE FROM BOARD_SCHEDULE WHERE PST_ID = 'BRDDEMO003';
DELETE FROM BOARD_TODO_ASSIGNEE WHERE PST_ID = 'BRDDEMO004';
DELETE FROM BOARD_TODO WHERE PST_ID = 'BRDDEMO004';
DELETE FROM BOARD_SHARE_RECIPIENT WHERE PST_ID = 'BRDDEMO006';
DELETE FROM BOARD_SHARE WHERE PST_ID = 'BRDDEMO006';
DELETE FROM BOARD_REPORT WHERE PST_ID = 'BRDDEMO001';
DELETE FROM BOARD WHERE PST_ID IN ('BRDDEMO001', 'BRDDEMO002', 'BRDDEMO003', 'BRDDEMO004', 'BRDDEMO005', 'BRDDEMO006');

WITH ctx AS (
    SELECT COALESCE(
        MAX(CASE WHEN COMMUNITY_NM = U&'\BAA8\B450\C758\0020\B7EC\B2DD\0020\B77C\C6B4\C9C0' AND COMMUNITY_TYPE_CD = 'general' THEN COMMUNITY_ID END),
        MIN(COMMUNITY_ID)
    )::bigint AS COMMUNITY_ID
    FROM COMMUNITY
)
INSERT INTO BOARD (
    BBS_CTGR_CD, COMMUNITY_ID, CONTENTS, CRT_USER_ID, DEL_YN, FIXED_YN, FRST_CRT_DT,
    IMPORTANCE_CD, LAST_CHG_DT, LAST_CHG_USER_ID, LINK_URL, PST_FILE_ID, PST_ID, PST_TTL,
    COMMUNITY_AUTHOR_ROLE_CD,
    PST_TYPE_CD, PUBLISHED_DT, PUBLISH_STATE_CD, RESERVED_PUBLISH_DT, VIEW_CNT, VISIBILITY_CD
)
SELECT 'F101', NULL, '<p>게시판 워크스페이스가 적용되었습니다. 상단공지, 관심글, 설문, 일정, 할일을 이 화면에서 함께 확인하세요.</p>', 'admin', 'N', 'Y', CAST(CURRENT_TIMESTAMP - INTERVAL '5 days' AS TIMESTAMP), 'notice', CAST(CURRENT_TIMESTAMP - INTERVAL '5 days' AS TIMESTAMP), 'admin', NULL, NULL, 'BRDDEMO001', '게시판 워크스페이스 시작 안내', 'owner', 'story', CAST(CURRENT_TIMESTAMP - INTERVAL '5 days' AS TIMESTAMP), 'published', NULL::TIMESTAMP, 24, 'community'
FROM ctx
UNION ALL
SELECT 'F104', COMMUNITY_ID, '<p>이번 달 팀에서 먼저 정착할 게시판 기능을 선택해 주세요.</p>', 'user01', 'N', 'N', CAST(CURRENT_TIMESTAMP - INTERVAL '2 days' AS TIMESTAMP), 'important', CAST(CURRENT_TIMESTAMP - INTERVAL '2 days' AS TIMESTAMP), 'user01', NULL, NULL, 'BRDDEMO002', '이번 달 먼저 정착할 기능은?', 'member', 'poll', CAST(CURRENT_TIMESTAMP - INTERVAL '2 days' AS TIMESTAMP), 'published', NULL::TIMESTAMP, 17, 'community'
FROM ctx
UNION ALL
SELECT 'F104', COMMUNITY_ID, '<p>게시판 상세 화면과 권한 흐름을 함께 검토합니다. 예외 케이스와 연동 포인트를 준비해 주세요.</p>', 'admin', 'N', 'N', CAST(CURRENT_TIMESTAMP - INTERVAL '1 day' AS TIMESTAMP), 'event', CAST(CURRENT_TIMESTAMP - INTERVAL '1 day' AS TIMESTAMP), 'admin', NULL, NULL, 'BRDDEMO003', '게시판 개선 워크숍 일정', 'owner', 'schedule', CAST(CURRENT_TIMESTAMP - INTERVAL '1 day' AS TIMESTAMP), 'published', NULL::TIMESTAMP, 9, 'community'
FROM ctx
UNION ALL
SELECT 'F105', COMMUNITY_ID, '<p>각 담당자는 게시판 마감 항목 한 가지씩 점검하고 이번 주 안에 진행 상태를 업데이트해 주세요.</p>', 'admin', 'N', 'N', CAST(CURRENT_TIMESTAMP - INTERVAL '18 hours' AS TIMESTAMP), 'urgent', CAST(CURRENT_TIMESTAMP - INTERVAL '18 hours' AS TIMESTAMP), 'admin', NULL, NULL, 'BRDDEMO004', '게시판 마감 점검 할일', 'owner', 'todo', CAST(CURRENT_TIMESTAMP - INTERVAL '18 hours' AS TIMESTAMP), 'published', NULL::TIMESTAMP, 13, 'community'
FROM ctx
UNION ALL
SELECT 'F104', COMMUNITY_ID, '<p>내일 오전 게시판 변경 사항이 반영됩니다. 예약 글 노출과 공지 영역을 다시 확인해 주세요.</p>', 'admin', 'N', 'N', CAST(CURRENT_TIMESTAMP - INTERVAL '2 hours' AS TIMESTAMP), 'normal', CAST(CURRENT_TIMESTAMP - INTERVAL '2 hours' AS TIMESTAMP), 'admin', NULL, NULL, 'BRDDEMO005', '내일 게시판 배포 안내', 'owner', 'story', NULL::TIMESTAMP, 'scheduled', CAST(CURRENT_TIMESTAMP + INTERVAL '1 day' AS TIMESTAMP), 0, 'community'
FROM ctx
UNION ALL
SELECT 'F106', NULL, '<p>특정 동료와만 공유한 비공개 검토 메모입니다.</p>', 'admin', 'N', 'N', CAST(CURRENT_TIMESTAMP - INTERVAL '6 hours' AS TIMESTAMP), 'important', CAST(CURRENT_TIMESTAMP - INTERVAL '6 hours' AS TIMESTAMP), 'admin', 'https://localhost:5173/board', NULL, 'BRDDEMO006', '비공개 검토 메모', 'owner', 'story', CAST(CURRENT_TIMESTAMP - INTERVAL '6 hours' AS TIMESTAMP), 'published', NULL::TIMESTAMP, 3, 'private'
FROM ctx;

INSERT INTO BOARD_POLL (PST_ID, ANONYMOUS_YN, DEADLINE_DT, MULTIPLE_YN, PARTICIPANT_OPEN_YN, RESULT_OPEN_YN)
VALUES ('BRDDEMO002', 'N', CURRENT_TIMESTAMP + INTERVAL '3 days', 'N', 'Y', 'Y');

INSERT INTO BOARD_POLL_OPTION (PST_ID, OPTION_TEXT, SORT_ORDR)
VALUES
    ('BRDDEMO002', '이야기와 댓글부터 정착하기', 1),
    ('BRDDEMO002', '설문 기능 먼저 사용하기', 2),
    ('BRDDEMO002', '일정 연동부터 마무리하기', 3);

INSERT INTO BOARD_POLL_RESPONSE (OPTION_ID, PST_ID, USER_ID)
SELECT OPTION_ID, PST_ID, 'admin' FROM BOARD_POLL_OPTION WHERE PST_ID = 'BRDDEMO002' AND SORT_ORDR = 2;
INSERT INTO BOARD_POLL_RESPONSE (OPTION_ID, PST_ID, USER_ID)
SELECT OPTION_ID, PST_ID, 'user02' FROM BOARD_POLL_OPTION WHERE PST_ID = 'BRDDEMO002' AND SORT_ORDR = 1;

INSERT INTO BOARD_SCHEDULE (PST_ID, ALLDAY_YN, END_DT, MEETING_RESERVATION_ID, MEETING_ROOM_ID, PLACE_TEXT, PLACE_URL, REMINDER_MINUTES, REPEAT_RULE, START_DT, VIDEO_MEETING_YN)
VALUES ('BRDDEMO003', 'N', CURRENT_TIMESTAMP + INTERVAL '1 day 11 hours', NULL, NULL, '프로덕트 스튜디오', NULL, 30, 'weekly', CURRENT_TIMESTAMP + INTERVAL '1 day 10 hours', 'N');

INSERT INTO BOARD_SCHEDULE_ATTENDEE (PST_ID, USER_ID, ATTENDANCE_STTS_CD)
VALUES ('BRDDEMO003', 'admin', 'accepted'), ('BRDDEMO003', 'user01', 'accepted'), ('BRDDEMO003', 'user02', 'invited');

INSERT INTO BOARD_TODO (PST_ID, DUE_DT, STATUS_CD)
VALUES ('BRDDEMO004', CURRENT_TIMESTAMP + INTERVAL '4 days', 'in_progress');

INSERT INTO BOARD_TODO_ASSIGNEE (PST_ID, STATUS_CD, USER_ID)
VALUES ('BRDDEMO004', 'in_progress', 'user01'), ('BRDDEMO004', 'requested', 'user02');

INSERT INTO BOARD_POST_REACTION (PST_ID, REACTION_CD, USER_ID)
VALUES ('BRDDEMO001', 'like', 'user01'), ('BRDDEMO001', 'like', 'user02'), ('BRDDEMO002', 'like', 'admin');

INSERT INTO BOARD_POST_MENTION (PST_ID, USER_ID)
VALUES ('BRDDEMO001', 'user01'), ('BRDDEMO001', 'user02');

INSERT INTO BOARD_COMMENT (CMNT_SQN, CMNT_FILE_ID, CONTENTS, CRT_USER_ID, DEL_YN, FRST_CRT_DT, LAST_CHG_DT, LAST_CHG_USER_ID, PST_ID, UP_CMNT_SQN)
VALUES
    ('CMNTDEMO001', NULL, '상단공지 게시물에 변경 내용을 정리해 두면 처음 들어온 사람도 이해하기 좋겠습니다.', 'user01', 'N', CURRENT_TIMESTAMP - INTERVAL '4 days 22 hours', CURRENT_TIMESTAMP - INTERVAL '4 days 22 hours', 'user01', 'BRDDEMO001', NULL),
    ('CMNTDEMO002', NULL, '동의합니다. 상세 화면에서 좋아요와 읽은 사람도 더 분명하게 보여주면 좋겠습니다.', 'admin', 'N', CURRENT_TIMESTAMP - INTERVAL '4 days 20 hours', CURRENT_TIMESTAMP - INTERVAL '4 days 20 hours', 'admin', 'BRDDEMO001', 'CMNTDEMO001');

INSERT INTO BOARD_COMMENT_MENTION (CMNT_SQN, USER_ID)
VALUES ('CMNTDEMO002', 'user01');

INSERT INTO USER_FEED_READ (USER_ID, PST_ID, READ_DT)
VALUES
    ('admin', 'BRDDEMO001', CURRENT_TIMESTAMP - INTERVAL '1 day'),
    ('user01', 'BRDDEMO001', CURRENT_TIMESTAMP - INTERVAL '1 day'),
    ('user02', 'BRDDEMO001', CURRENT_TIMESTAMP - INTERVAL '12 hours'),
    ('admin', 'BRDDEMO002', CURRENT_TIMESTAMP - INTERVAL '6 hours');

INSERT INTO USER_SAVED_POST (USER_ID, PST_ID, CRT_DT)
VALUES ('admin', 'BRDDEMO004', CURRENT_TIMESTAMP - INTERVAL '2 hours'), ('user01', 'BRDDEMO002', CURRENT_TIMESTAMP - INTERVAL '2 hours');

INSERT INTO BOARD_REPORT (PST_ID, REASON_TEXT, REPORTER_ID, STATUS_CD)
VALUES ('BRDDEMO001', '관리자 신고 흐름 확인용 데모 데이터입니다.', 'user02', 'submitted');

WITH share_row AS (
    INSERT INTO BOARD_SHARE (PST_ID, SHARE_TARGET_ID, SHARE_TYPE_CD, SHARE_USER_ID)
    VALUES ('BRDDEMO006', 'user02', 'user', 'admin')
    RETURNING SHARE_ID
)
INSERT INTO BOARD_SHARE_RECIPIENT (PST_ID, RECIPIENT_USER_ID, SHARE_ID)
SELECT 'BRDDEMO006', 'user02', SHARE_ID
FROM share_row;

COMMIT;
